### ISSUE TITLE
smart_open in other languages

### ISSUE THREAD

**Issue by modqhx** [RaRe-Technologies/smart_open#104]
I have a few questions:
- Is "smart open" (or something similar) available in other languages? (like maybe GO, or java)
- Does the [gensim](https://github.com/RaRe-Technologies/gensim) library from same group use this same tool/ approach? 
- I see running things like streaming in data from s3 is very CPU( and IO) intensive and not much memory intensive. Would multi-threading approach a good way to parallelize reading many and huge files(logs) from s3?  Or would it be worthless?, let's say if I'm parsing the json and then writing to a relational data warehouse; since the write on the db would be single threaded?

**Comment by menshikh-iv** [comment]
Hi @modqhx, sorry for late answer

1. Probably yes, but not from us, we have only python version
2. gensim use `smart_open` almost always (especially for `save`/`load` stuff)
3. If you will read in multiple threads & write with one thread, probably bottleneck will be in DB writing in this case (read more per sec that you can write), in some cases it can work (with very fast databases), but in general, the idea isn't the best.
