### ISSUE TITLE
Gzipped Files Over HTTPS Lacking the tell()

### ISSUE THREAD

**Issue by mcrowson** [RaRe-Technologies/smart_open#119]
Doing a `smart_open('https://url/file.xml.gz')` uses passes the ReadStream to the GzipFile during the make_compression

The file object passed here is the HttpReadStream
https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/smart_open_lib.py#L632

The read stream doesn't have the tell() method that the gzip library expects.

**Comment by mcrowson** [comment]
In Python2.7 the read() method on gzip expects tell. https://github.com/python/cpython/blob/2.7/Lib/gzip.py#L285 

It looks like the call to tell was deprecated in Py3.2

**Comment by tmylk** [comment]
Thanks for reporting it. Does it also happen on the develop branch? Similar issue has been fixed recently with [tests](https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/tests/test_smart_open.py#L135) added.

Will make a new release this week.

**Comment by mcrowson** [comment]
Ah, I see 1.5.2 fixes this, thanks with the BytesIO fileobj. Thanks!
