### ISSUE TITLE
S3 does not work with AWS Instance Roles

### ISSUE THREAD

**Issue by awm33** [RaRe-Technologies/smart_open#122]
Since this uses an old version of boto, it will not load instance role credentials, making it unusable in a typical AWS production environment,

**Comment by tmylk** [comment]
Thanks for reporting it. What is a good new version of boto to use?
Do you have a code snipped to reproduce?

**Comment by piskvorky** [comment]
@tmylk that's issue #43 , I believe.

If boto3 is finally production ready now (is it?), we should definitely switch.

**Comment by vinuthna91** [comment]
Hi for me I see data corruption while writing to a avro on S3. Is it expected?

**Comment by menshikh-iv** [comment]
duplicate of #43 (need to move to `boto3`)
