### ISSUE TITLE
S3ResponseError: S3ResponseError: 403 Forbidden <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><RequestId>tx000000000000000017e26-00592d7954-ac95-default</RequestId><HostId>ac95-default-default</HostId></Error>

### ISSUE THREAD

**Issue by vinuthna91** [RaRe-Technologies/smart_open#124]
Traceback (most recent call last):
  File "/home/vvinjamuri/datahighway/DataIngestionS3/Python/avroConverterS3.py", line 222, in generateAvroFromCSVS3
    for line in fin:
  File "/usr/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 402, in __iter__
    for line in self.reader:
  File "/usr/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 374, in readline
    result = super(S3ReadStream, self).readline(*args, **kwargs)
  File "/usr/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 330, in readinto
    data = self.read(len(b))
  File "/usr/anaconda/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 318, in read
    raw = self.stream.read(io.DEFAULT_BUFFER_SIZE)
  File "/usr/anaconda/lib/python2.7/site-packages/boto/s3/key.py", line 396, in read
    self.open_read()
  File "/usr/anaconda/lib/python2.7/site-packages/boto/s3/key.py", line 303, in open_read
    self.resp.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><RequestId>tx000000000000000017e27-00592d7954-ac95-default</RequestId><HostId>ac95-default-default</HostId></Error>

_Following is the code, that is causing this error-

inConn = boto.connect_s3(
           aws_access_key_id = access_key,
           aws_secret_access_key = secret_key,
               port=<portnum>,
              host = <hostname>,
               is_secure=False,
                calling_format = boto.s3.connection.OrdinaryCallingFormat(),
              )

 inbucket = inConn.get_bucket('my_bucket',validate=False)
kr=inbucket.get_key('my_key.csv',validate=False)

with smart_open.smart_open(kr,'rb') as fin:
               print fin
               for line in fin:
                     print line_

**Comment by menshikh-iv** [comment]
Looks strange `InvalidAccessKeyIdtx000000000000000017e27-00592d7954-ac95-defaultac95-default-default`, please check your keys for amazon

**Comment by mpenkov** [comment]
@vinuthna91 Are you still experiencing this problem? Could you please confirm that your key works with other tools, like the AWS CLI?

**Comment by menshikh-iv** [comment]
Unreproducable with current master fbc82cc04bf92e8c588c49c43ff5aff8234ea87d (probable problems with creds)

```python
import boto
import smart_open

conn = boto.connect_s3(is_secure=False, calling_format=boto.s3.connection.OrdinaryCallingFormat())
inbucket = conn.get_bucket('test-gensim', validate=False)

kr = inbucket.get_key('Redirecting.txt', validate=False)

with smart_open.smart_open(kr, 'rb') as fin:
    print(fin)
    for line in fin:
        print(line)
```
