### ISSUE TITLE
FTP Question

### ISSUE THREAD

**Issue by lbrent2k** [RaRe-Technologies/smart_open#138]
Would I be able to use this to move a file _directly_ from FTP server to S3 without storing at disk at any point?  Thanks.

**Comment by mpenkov** [comment]
There is already a component to write to S3. It writes on the fly, and does not require you to store data locally. However, the data doesn't move from FTP _directly_ to S3: it goes through the machine running smart_open first.

The other hurdle is that currently smart_open does not read from FTP (see issue #33).
