### ISSUE TITLE
HDFS, WebHDFS, HTTP I/O is not encoding-aware

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#146]
The HDFS and Http subsystems does not do any text encoding or decoding.

- HdfsOpenRead returns the stdout from a Popen, so it will be in whatever encoding Popen uses for pipes (could be UTF-8, or raw bytes)
- HdfsOpenWrite writes bytes directly into the stdin of a Popen
- WebHdfsOpenRead reads bytes directly (requests.get returns bytes when `stream=True`)
- HttpOpenRead also reads bytes directly (uses requests in the same manner as above).

**Comment by mpenkov** [comment]
I think this is resolved by #185

**Comment by menshikh-iv** [comment]
@mpenkov :+1:
