### ISSUE TITLE
Support for opening `pathlib.Path`

### ISSUE THREAD

**Issue by clintval** [RaRe-Technologies/smart_open#170]
Would you be willing include support for the standard library `Path` object?

```python
>>> from pathlib import Path
>>> from smart_open import smart_open

>>> path = Path('~/test.txt').expand_user().resolve()
>>> smart_open(path)

TypeError: don't know how to handle uri PosixPath('/home/user/test.txt')
```

I would be willing to create the PR! Thanks!

**Comment by clintval** [comment]
No benefit except for duck-typing.

If parity with `open()` is a goal of this project than it would make sense for it be supported. No worries if not!

**Comment by mpenkov** [comment]
If this improves parity, then it makes sense.

@menshikh-iv what do you think?
