### ISSUE TITLE
ignore_extension not supported on file_smart_open

### ISSUE THREAD

**Issue by shmuelamar** [RaRe-Technologies/smart_open#172]
hi, I'm using this great library and noticed `ignore_extension` is only supported on S3. I'm willing to submit a PR for fixing this for `file_smart_open` if this is desired.

my usecase is concatenating gzip files from both S3 and local filesystem into a single file. to get better performance I am concatenating the gzip files as binaries instead of decompressing, concat and then compress to single file (gzip format allows to chain multiple gzip streams one after another).

**Comment by menshikh-iv** [comment]
Hello @shmuelamar, interesting, can you demonstrate some examples (how it should looks)?

**Comment by mpenkov** [comment]
@menshikh-iv I think this got resolved via pull request #185

**Comment by menshikh-iv** [comment]
Yes, you are right, thanks @mpenkov!
