### ISSUE TITLE
Don't swallow ClientError when bucket doesn't exist

### ISSUE THREAD

**Issue by FragLegs** [RaRe-Technologies/smart_open#174]
In `smart_open.s3.BufferedOutputBase.__init__()` (lines 339-342) why does this library swallow the botocore ClientError and return a ValueError? It makes it tricky to handle the error case properly.

**Comment by mpenkov** [comment]
From memory, it is because we try to mimic the built-in open.

@menshikh-iv What do you think? Should we just allow the ClientError to be raised?

**Comment by menshikh-iv** [comment]
@FragLegs  we really mimic python `open`, for this reason, we use standard exceptions (user shouldn't remember about `botocore.client.ClientError`, but can easily catch `ValueError`).

I don't think that this is an issue, @piskvorky through?

**Comment by FragLegs** [comment]
That makes sense. However, when you try to open an s3 key that doesn’t exist (in a bucket that does exist) you get a `botocore.client.ClientError`. Perhaps that is the thing that should change?

Note: I’m not at my computer right now, but I’m pretty sure that’s the behavior I was seeing earlier today. I’ll reconfirm tomorrow. 

Would it make sense to put some info about the ClientError in the raised ValueError?

**Comment by menshikh-iv** [comment]
@FragLegs 

> Would it make sense to put some info about the ClientError in the raised ValueError?

This is definitely a good idea, PR are welcome!

**Comment by FragLegs** [comment]
Great! I'll issue one as soon as I can. Thanks!
