### ISSUE TITLE
Support for reading S3 Object for a given Object Version ID

### ISSUE THREAD

**Issue by michael-robbins** [RaRe-Technologies/smart_open#181]
Currently we can only read the 'latest' object version when reading an S3 URI.

Off the top of your head(s), would this already be supported somehow? Or would we need to update a lot of code to support this?

**Comment by mpenkov** [comment]
It's not something we've thought of at all when writing the S3 code.

I don't know how extensive the changes required to support previous versions would be, but yes, you'd have to edit a bit of code. My guess is at the very least you'll have to propagate the version desired from the public API to the S3 module, and then add support for multiple versions within that module.
