### ISSUE TITLE
S3.py use the rangestring without end?

### ISSUE THREAD

**Issue by inksink** [RaRe-Technologies/smart_open#183]
When I have a 30G object, maybe I only want to read front several bytes but I will read the whole object!

**Comment by piskvorky** [comment]
`smart_open` uses streaming to read data from S3.

If you have a concrete bug report, please include instructions for reproducing the issue.

**Comment by inksink** [comment]
Sorry, there's some bad description in my previous comment.

Suppose `s3://test/test` is a 30G object. Run the code below in IPython. 
```
# ipython
import smart_open
f = smart_open.s3.open("test","test","rb")
f.read(1)
```
Then I will see that the memory of this process will increase to 30G (if you have) .

**Comment by piskvorky** [comment]
Oh, if that is true, then it's a bug. Read should be buffered/stream.

Can you make your example reproducible, using a concrete S3 file?

**Comment by inksink** [comment]
Hmmmm, it seems that I made a mistake. 
When I run these codes, the memory of my proxy to s3 will increase, not these codes.
Sorry, I will close this issue and do more tests for it.
