### ISSUE TITLE
S3 old object body was not closed after seek()

### ISSUE THREAD

**Issue by inksink** [RaRe-Technologies/smart_open#187]
In class SeekableRawReader:
If we seek(), self._body will be replaced with a new object['Body']:
```
self._body = self._object.get(Range=range_string)['Body']
```
But old body should been closed. Why not : 
```
self._body.close()
self._body = self._object.get(Range=range_string)['Body']
```

**Comment by mpenkov** [comment]
I think once the function exits, the old body will get garbage-collected and closed then. I don't have anything to back this up.

However, I agree that closing it explicitly is a better idea. May be worth checking for None before the close.

Are you able to make a PR?

**Comment by inksink** [comment]
OK I will make a PR tomorrow

杨阳



On Mon, Apr 9, 2018 at 8:08 PM +0800, "Michael Penkov" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think once the function exits, the old body will get garbage-collected and closed then. I don't have anything to back this up.

However, I agree that closing it explicitly is a better idea. May be worth checking for None before the close.

Are you able to make a PR?
