### ISSUE TITLE
Support for GCS

### ISSUE THREAD

**Issue by Arvinds-ds** [RaRe-Technologies/smart_open#198]
Do you have plans to support the Google Cloud Storage protocol `gcs://`

**Comment by piskvorky** [comment]
Sounds like a good idea to me. No concrete plans yet -- do you want to implement this?

**Comment by petedannemann** [comment]
I am working on adding GCS support and wanted to ask a question before I get too deep into the code. I can create a new issue and repost the question there if this is the wrong place to ask it.

Will future smart-open releases support Python 2.7?

**Comment by mpenkov** [comment]
I don't think so. There is little value of spending effort supporting a language that even the language creators no longer support ([Py2.7 end of life is Jan 1 2020](https://pythonclock.org/)).

That said, the library doesn't depend on the Python version _that_ much, so the effort of maintaining support for 2.7 is probably much less than for e.g. gensim.

Why do you ask?

**Comment by petedannemann** [comment]
GCS support will just require a substantial amount of code to be added (similar to the amount of S3) and I wasn't sure how much I should focus on backwards compatibility. We can revisit this once I've actually completed the code and submitted a PR.

**Comment by mpenkov** [comment]
In general, aim for Py3. It's unlikely you'll finish this before the end of the year, and Py2 will be gone by then.

**Comment by petedannemann** [comment]
Can we close this?

**Comment by mpenkov** [comment]
Yes, thank you for following up.
