### ISSUE TITLE
Improve tooling for repository

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/smart_open#216]
We need to improve the tooling of the repository to increase code-quality and simplify test process
- [x] Add style-checker (pycodestyle, flake8, any)
- [x] Add tox that should allow
  - [x] Run tests with all python version
  - [x] Run style-checkers
  - [x] (optional) Run integration tests

**Discussion:** @piskvorky @mpenkov wdyt to add automatic code-formatter like  https://github.com/google/yapf or https://github.com/ambv/black, I want to drop all discussions about code-style at all (honestly, I want to do it for Gensim, but `smart_open` are good candidate for test this approach, because it simple and small).

Why I think this is useful:
- auto code-formatting (no need to remember about style always)
- no comments about code-formatting
- always clean code

**Comment by piskvorky** [comment]
Fine with me (of course), good idea. As long as we can enforce, or at least allow, hanging indent (not vertical) and lines longer than 80 chars.
