### ISSUE TITLE
Travis CI: Why does enabling sudo cause the tests to fail?

### ISSUE THREAD

**Issue by cclauss** [RaRe-Technologies/smart_open#218]
Demonstrated: #217 Output: https://travis-ci.org/RaRe-Technologies/smart_open/builds/413337196

Blocks #215

**Comment by menshikh-iv** [comment]
@cclauss I think that's a question to `boto3` team, can you submit an issue to https://github.com/boto/boto3?

**Comment by cclauss** [comment]
https://github.com/boto/boto3/blob/develop/.travis.yml#L23-L25

**Comment by menshikh-iv** [comment]
@cclauss That's not an answer to the question "why this happens", I see that it works in the `boto3` repo, but this is different way of installation (we using PyPI, `boto3` use `boto3` repo).
