### ISSUE TITLE
Streaming many 200mb files to s3 - is this the right library? 

### ISSUE THREAD

**Issue by trentgerman** [RaRe-Technologies/smart_open#220]
Hi all - 

The header says it all! I'm looking for a way to stream ~30 200 mb files to s3. would you say this is the correct library to do so? I'd like to do this in a way that is async using python 2.7, and I've had some trouble doing this task.

One thing I've noticed is that smart_open seems to fail if I make a call within a python multiprocessing.process. I believe this is actually some issue with boto3. I'm thinking boto3 cannot find the right aws_profile_name I'm using (or other credentials) inside of the multiprocessing.Process? Maybe I'm mistaken as to the true cause, though. I get a an os error with fork when I do so. 

Anyways, I'm curious how other's would accomplish this task. Maybe calling smart_open inside of a grevent thread or some other IO specific thread is the right way? 

cheers, 

Trent

**Comment by menshikh-iv** [comment]
> would you say this is the correct library to do so?

yes

30 files looks not so much, can be easily done in sequential model (without any multiprocessing), but if you really needed - can you please share your current code (that raise an Exception) with full trace, we'll have a look.

as idea, what's about standart threads (most of this task are IO -> GIL released ->  should works OK with standart threads)?

**Comment by trentgerman** [comment]
Just to update, I used standard threads and that worked great! 

+1 for using the simplest solution, even though I didn't end up using your library. 

Thank you!

-Trent
