### ISSUE TITLE
upload remote file to S3 using this library

### ISSUE THREAD

**Issue by hyphen1370** [RaRe-Technologies/smart_open#226]
Hello, 

I would like to use this library to stream a file from URL to S3. 

Here is the code I tried:

    smart_open_s3_uri = 's3://' + aws_access_key + ':' + aws_SecretAccess_key + '@' + event['S3Bucket'] + '/' + event['S3KeyPath']
    print(smart_open_s3_uri)

    with smart_open(smart_open_s3_uri, 'wb') as fout:
        for line in smart_open(event['MediaURL']):
            print(line)
            fout.write(line)

However, it doesn't do anything, no message return. 

I also try to do 

s3_response = requests.get(event['MediaURL'], stream=True)

    with smart_open(smart_open_s3_uri, 'wb') as fout:
        for line in s3_response.raw:
            print(line)
            fout.write(line)

It doesn't do anything, no message return. 

So, what is correct way to do this?

Thanks

**Comment by mpenkov** [comment]
If you don't see anything on standard output, then perhaps whatever you're trying to write is empty? 

What do you see if you do:

    aws s3 cp s3://whatever/the/event/media/url/is test.dat
    ls -lh test.dat

from the command line?

**Comment by hyphen1370** [comment]
I am sorry that I can't do the cp command since the file is not showing up in S3. The event['MediaURL'] contains a URL generate from Twilio, like

https://api.twilio.com/2010-04-01/Accounts/AC45215bd3e339f0374b99a1272d42c5e1/Messages/MM4da22524eab6f965d87f34329f8bcd3e/Media/MEcb9bc0b863fd6c29517519d83d387d83

which publicly accessible. 
This URL redirect to
https://s3-external-1.amazonaws.com/media.twiliocdn.com/AC45215bd3e339f0374b99a1272d42c5e1/2fa73b761d5e84dc3c88f14c99e99b0d

So, is that 'wb' mode create file and then write to it? Or the file needs to create it first, and then write to it? 

Thanks

**Comment by hyphen1370** [comment]
So, do you know why it doesn't any message return? Is that redirect URL being the problem?

**Comment by mpenkov** [comment]
I think you need to debug your code.

Try something like:

```python
url = "https://api.twilio.com/2010-04-01/Accounts/AC45215bd3e339f0374b99a1272d42c5e1/Messages/MM4da22524eab6f965d87f34329f8bcd3e/Media/MEcb9bc0b863fd6c29517519d83d387d83"
with smart_open.smart_open(url) as fin:
    data = fin.read()

print("read %d bytes" % len(data))
# maybe also save the file locally and check that it downloaded correctly

with smart_open.smart_open(output_s3_url, "wb") as fout:
    fout.write(data)

# compare the local file with the uploaded file
```

If everything checks out, then you can start read-writing on the fly.

**Comment by hyphen1370** [comment]
Figured out the issue, it looks like the package has to run under python 3.6. I used the pip3 install smart_open -t <directory> and it works. It doesn't work when I use pip

**Comment by menshikh-iv** [comment]
@hyphen1370 that's strange because of smart open support python `2.7` and `3.3+` (@mpenkov code should work for both python versions)

**Comment by hyphen1370** [comment]
Hello, 

One more issue, every file uploaded to S3 has the same content type "binary-ostream". Is there anyway to set content-type while uploading/streaming file to S3 using smart_open?

**Comment by mpenkov** [comment]
I don't think so. You may have to use boto3 to do that explicitly after streaming.

**Comment by menshikh-iv** [comment]
So, I think I can close this thread (no bug in `smart_open`)
