### ISSUE TITLE
Support Azure BLOB storage

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/smart_open#228]
Add a connector for Azure blob storage, original request - https://github.com/RaRe-Technologies/gensim/issues/2184

**Comment by sd1998** [comment]
@menshikh-iv I would like to work on this.

**Comment by menshikh-iv** [comment]
@sd1998 feel free to contribute

**Comment by miraculixx** [comment]
I am interested in this too, what is the canonical way to extend `smart_open` with a new scheme/backend?

**Comment by mohithg** [comment]
Is there any progress on this?

**Comment by nclsmitchell** [comment]
I am interesting to develop this feature, I will open a new PR when finished
