### ISSUE TITLE
Return number of bytes written from `write()`

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/smart_open#231]
Python3 `write()` is expecting to return the number of bytes written. `smart_open`'s write doesn't return anything (`None`).

Addressed in #132 but PR abandoned -- requires a unit test before merge.

**Comment by mpenkov** [comment]
Works on master:

```python
>>> import io
>>> import smart_open
>>> buf = io.BytesIO()
>>> fout = smart_open.smart_open(buf, 'wb')
>>> fout.write(b'hello')
5
>>> buf.getvalue()
b'hello'
```

Must've gotten fixed along the way somewhere.
