### ISSUE TITLE
chunk load save?

### ISSUE THREAD

**Issue by rizplate** [RaRe-Technologies/smart_open#233]
processing line by line is takes very long time on big files.

does this support chunksize or num_lines etc, so that large files can be processed in big batches?

**Comment by menshikh-iv** [comment]
> does this support chunksize or num_lines etc

as I remember - no, but `smart_open` has an internal buffer, i.e. fetch N bytes at once (not 1 by 1).
CC: @mpenkov

**Comment by mpenkov** [comment]
If fetching things line-by-line doesn't work, then you can always open the remote file as binary and do your own buffering.

**Comment by piskvorky** [comment]
@rizplate what file scheme are you streaming from? (s3, local, hdfs…)

Also, what is "very long time" on "big" files, concretely?

**Comment by rizplate** [comment]
@piskvorky I am using s3 and file size is around 1TB.

 I need to do some processing before fetching next line, and I can not store whole thing locally right away. That is why I was wondering if any chunksize is supported so that network latency is not bottleneck on the internal buffer

**Comment by menshikh-iv** [comment]
@rizplate as @mpenkov suggested - you can implement your own buffering with binary mode

**Comment by mpenkov** [comment]
@menshikh-iv Actually, it's not even necessary to use binary mode in this case. @rizplate has indicated that he's processing the file _line by line_ and that the processing takes time. So, @rizplate needs to implement their own line-based buffer.

**Comment by piskvorky** [comment]
AFAIK the S3 reader in `smart_open` already does line buffering, like @menshikh-iv said. What would @rizplate gain by re-implementing that? I don't follow.

**Comment by mpenkov** [comment]
@piskvorky We don't allow the user to specify the buffer size. We also don't implement a rolling buffer - we read the current buffer to the end before loading any new data.

Doing the buffering themselves would enable the user to do the above.

**Comment by piskvorky** [comment]
Wouldn't a rolling buffer means even more requests/latency? That doesn't sound like a solution.

Buffering doesn't seem what @rizplate needs; rather, he need to be pre-loading the lines in the background, in a separate I/O thread, while the main thread is doing the line processing. AFAICT this can be done with existing `smart_open` already, no difference to us.

**Comment by rizplate** [comment]
@piskvorky yes I just need a big buffer to be read, process it and then the request for same buffer size needs to go. 

I was hoping that I can just set some buffer-size/chunk setting on smart_open. And it would read that chunk, let me process it, and then make next call to read remaining of s3 chunk-by-chunk. preferably I would like to read 64 mb , process it and then have the next request be sent for another 64 mb, till the file is exhausted. 

I will try setting smart_open.s3.DEFAULT_BUFFER_SIZE to see if it can be used.

**Comment by piskvorky** [comment]
@rizplate that's exactly how smart_open already works, so I suspect your real bottleneck/issue is something else.
