### ISSUE TITLE
Documentation dpesn't mention Python 3 support

### ISSUE THREAD

**Issue by EliYk** [RaRe-Technologies/smart_open#243]
Hi, 

Sweet library, thank you. 

Wanted to point out that If someone reads the official doc - 
https://smart-open.readthedocs.io/en/latest/

and doesn't check the github, he may be under the impression smart_open only works with python 2.

Cheers,
Eli

**Comment by menshikh-iv** [comment]
Hi @EliYk, 

thanks for report. To be honest, I have no idea who controls https://smart-open.readthedocs.io/en/latest/, @piskvorky through? Looks outdated.

Just for clarity: right now we support `2.7`, `3.5`, `3.6` and 3.7`

**Comment by piskvorky** [comment]
It looks like I added `smart_open` to RTD long, long time ago (and then forgot).

I deleted it now, so it doesn't confuse people.
