### ISSUE TITLE
Make metadata accessible

### ISSUE THREAD

**Issue by eode** [RaRe-Technologies/smart_open#249]
Hi, I was wondering if you could make metadata accessible as well -- I.e., what you get from `s3_client.head_object(Key=key, Bucket=bucket)['Metadata']`.

Perhaps stored at `some_s3_f_obj.metadata` -- though, it might need to be given before writing, either at object open time, or assigned before the first write (depending on how you handle writes).

Thanks for the great tool!

**Comment by mpenkov** [comment]
I think that would involve duplicating functionality that is already in boto3, as you've demonstrated in your example.

What would be the benefit of doing this over accessing the metadata via boto3 directly?

**Comment by eode** [comment]
Upload is the only critical one, but implementing both would have this
primary and critical benefit:
  * Allow setting of metadata when using `smart_upload` which, with some
weird exceptions, is currently unsettable with `smart_open`
    * Weird exception: Uploading the wrong name, then using the AWS API to
copy the file to the right name, with the right metadata
..and these tertiary benefits:
  * Be a full abstraction of an S3 object instead of a partial one
  * Consistency in API -- what is readable is also writeable, where the
underlying medium supports it
..and, if S3/boto3 supports it (which it may not):
  * get the metadata at download time, without a separate `head` call

**Comment by eode** [comment]
Upload is the only critical one, but implementing both would have this
primary and critical benefit:

  * Allow setting of metadata when using `smart_upload` which, with some
weird exceptions, is currently unsettable with `smart_open`
    * Weird exception: Uploading the wrong name, then using the AWS API to
copy the file to the right name, with the right metadata
..and these tertiary benefits:
  * Be a full abstraction of an S3 object instead of a partial one
  * Consistency in API -- what is readable is also writeable, where the
underlying medium supports it
..and, if S3/boto3 supports it (which it may not):
  * get the metadata at download time, without a separate `head` call

**Comment by mpenkov** [comment]
We don't want to do this, by design.
