### ISSUE TITLE
Can't create anonymous client

### ISSUE THREAD

**Issue by kmax12** [RaRe-Technologies/smart_open#250]
I am trying to anonymously download a file from S3. Using the [S3Fs](https://s3fs.readthedocs.io/en/latest/) library I am able to do something like this 

```
s3 = s3fs.S3FileSystem(anon=False)
remote_archive = s3.open(uri, 'rb')
```

Looking at their source code they create an anonymous client like this

```
if self.anon:
    from botocore import UNSIGNED
    conf = Config(connect_timeout=self.connect_timeout,
                  read_timeout=self.read_timeout,
                  signature_version=UNSIGNED, **self.config_kwargs)
    if not self.passed_in_session:
        self.session = boto3.Session(**self.kwargs)
else:
    conf = Config(connect_timeout=self.connect_timeout,
                  read_timeout=self.read_timeout,
                  **self.config_kwargs)
    if not self.passed_in_session:
        self.session = boto3.Session(self.key, self.secret, self.token,
                                     **self.kwargs)

s3 = self.session.client('s3', config=conf, use_ssl=ssl,
                         **self.client_kwargs)
```

however, I only see the option in `smart_open` to pass in a session, not a client.

How can I create an anonymous client in smart_open?

**Comment by mpenkov** [comment]
@kmax12 We don't support this yet, but it should be possible: https://stackoverflow.com/questions/34865927/can-i-use-boto3-anonymously

Basically, we need to pass a separate set of parameters to the .client() function. Are you able to make a PR? If so, please have a look at the current master branch.

**Comment by mpenkov** [comment]
@kmax12 I did some digging, I think you should be able to satisfy your use case with:

```python
from smart_open import open
config = Config(signature_version=UNSIGNED)
params = {
    'resource_kwargs': {'config': config},
}
with open('s3://bucket/key', transport_params=params) as fin:
    ...
```

We don't use any Client objects. We use the resource directly. However, the resource objects accept the Config as keyword arguments the same way that Client objects do.

Please let me know if that works for you.

**Comment by rwedge** [comment]
@mpenkov that approach worked for me, thanks!
