### ISSUE TITLE
Upload zip files

### ISSUE THREAD

**Issue by leiserfg** [RaRe-Technologies/smart_open#257]
It's just an idea, you can use https://github.com/allanlei/python-zipstream as a weak dependency for doing that.

**Comment by menshikh-iv** [comment]
thanks for idea @leiserfg

**Comment by leiserfg** [comment]
I'm thinking about doing it myself this weekend. Should I add zipstream as a hard dependency or as an extra dependency?

**Comment by mpenkov** [comment]
The thing with zip-stream is its only one-way, right? It doesn't allow you to both read _and_ write zip files. I think if we go ahead with an implementation, we should make it bidirectional.

Before you go ahead, we should also discuss the API. zip files aren't just compressed, they're _archives_. So you need to work out a way to specify the member of the archive to read/write as well.

**Comment by leiserfg** [comment]
It will not work bidirectionally because not all zip can be decompressed with streams, depends on the algorithm and the flags used in the compression.

**Comment by leiserfg** [comment]
The name of the file can be set by using `#`  like `something.com/file.zip#text_file`  but it won't allow using multiple files so maybe is better to document how to use both libraries together in the readme.

**Comment by mpenkov** [comment]
I'm not sure if this use case is sufficiently broad to include it in the library. My arguments against:

1. unidirectional (write-only)
2. requires updating the URL format (hacky, I really don't like that idea, to be honest)
3. requires additional parameters for zip compression
4. tricky edge cases (e.g. using multiple files, as per your comment)

I think a better way to integrate zipfile would be _outside_ of the smart_open library. You could open a binary output stream to whichever destination you want, and then pass it to zipstream. Does that sound like it would work?

**Comment by mpenkov** [comment]
@leiserfg Any updates on this? If you got it working, we could include it in our documentation as an example or recipe.
