### ISSUE TITLE
List bucket - provide credentials

### ISSUE THREAD

**Issue by botzill** [RaRe-Technologies/smart_open#259]
Hi.

IS it possible to provide custom credentials when listing bucket? I see here https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/s3.py#L537 there is no way to provide params. 

Thx.

**Comment by mpenkov** [comment]
Currently, it is not possible. You have to ensure that boto3 picks up your credentials via is default mechanisms (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#method-parameters).

However, I think it would be relatively simple to implement in a PR. You'd need to pass the session parameters as kwargs to the s3_iter_bucket function. Are you able to make such a PR?

**Comment by Iamshankhadeep** [comment]
@mpenkov can I work on this issue?

**Comment by mpenkov** [comment]
Yes, please.

**Comment by Iamshankhadeep** [comment]
@mpenkov  Can you tell me the file I need to edit? I am fairly new on this any help will be appreciated.

**Comment by mpenkov** [comment]
Closed via https://github.com/RaRe-Technologies/smart_open/pull/372
