### ISSUE TITLE
Charges for Amazon S3 bucket

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/smart_open#275]
The free credits for our `rare-opensource` AWS account, which we're using to CI-test `smart_open`, have expired.

As a consequence, I will be terminating that account in a few days, because I don't want to be charged by AWS for an open source project.

@mpenkov do you know what we need that AWS account for? What will happen when it disappears?

Any ideas how to replace it with something free? (Amazon won't extend the free Activate credit, I already asked).

**Comment by mpenkov** [comment]
We need the AWS account for testing that smart_open actually works with Amazon S3 (integration tests).

I strongly recommend that we do _not_ terminate the account for the following reasons:

- Without it, we will be unable to know *for sure* that writing to S3 buckets works (very bad)
- Without it, we will have to work out a different place to store integration test results (inconvenient)
- It doesn't actually cost that much (fraction of a cent per GB storage/transfer)

Could you please have a look at what the potential costs would be?

**Comment by mpenkov** [comment]
@piskvorky Do you reckon we can close this?

**Comment by piskvorky** [comment]
Yes, let's close. The monthly bill is fairly small.
