### ISSUE TITLE
Best way to go to specific line in a CSV file streamed from HTTP?

### ISSUE THREAD

**Issue by jepmarketo** [RaRe-Technologies/smart_open#276]
I am using a Lambda function with a 5-minute timeout to stream data from a CSV file on HTTPS using csv DictReader. I can read about 3 million lines in 5 minutes, after which I save the `lines_processed` in DynamoDB. When I restart my Lambda function, I want to resume reading at `lines_processed`. 

I initially tried to use `seek`, but that didn't work well with DictReader. Now I'm reading through the file line-by-line and ignoring the data until `lines_processed`: see the code below, but I'm finding that simply reading through the file takes up most of the time, so when I resume, it takes at least 4 minutes to read through 3+ million lines. 

Any suggestions on how to speed up the resume process? Thanks!

```
batch = []
with smart_open.smart_open('https://example.com/test.csv', 'r') as f:
    reader = csv.DictReader(f)
    i = 0 
    for row in reader:
        i += 1
        if i > lines_processed:
            if len(batch) % 5000 == 0 and batch:
                lines_processed = i - 1
                yield batch, lines_processed
                del batch[:]
            batch.append(row)
```

**Comment by mpenkov** [comment]
> I can read about 3 million lines in 5 minutes, after which I save the lines_processed in DynamoDB.

Save the byte offset of the stream (you can get it with f.tell()). You can then seek to that offset and continue reading.

> I initially tried to use seek, but that didn't work well with DictReader.

I think the issue there is the DictReader needs access to the very first row of the CSV (the file header). Without it, DictReader would not know what the fields of the CSV are. I think you have two choices here:

1. Abandon DictReader and use the regular csv.reader
2. Wrap the stream such that it always serves the first line of the CSV first, before seeking to the previous offset and resuming

I recommend 1), it is simpler.

**Comment by jepmarketo** [comment]
Thanks, I hadn't thought about DictReader needing the column names in the first row. I will also try configuring DictReader to handle files without a header by explicitly specifying the columns. That would minimize the changes to my existing code.
