### ISSUE TITLE
Can't open S3 files with ?-like characters in name

### ISSUE THREAD

**Issue by hexvolt** [RaRe-Technologies/smart_open#285]
```
obj = smart_open.open(''s3://bucket-name/folder/picture #1.jpg', 'rb')
```
results to `the s3 key 'folder/picture ' does not exist, or is forbidden for access`.

At the same time 
```
s3_session.resource('s3').Bucket('bucket-name').download_file("folder/picture #1.jpg", "/tmp/test.jpg")
```
downloads the file successfully.

## Some investigation
Internally, `smart_open` takes unquoted value (`folder/picture #1.jpg`) and after parsing, it thinks that the path is `older/picture `  cutting the rest of the key.

I can try to feed it the quoted value (`folder/picture%20%231.jpg`) - in that case it will parse it correctly and will think that the whole thing is the key, but after that AWS won't understand this, as it's client (boto3?) requires values 'as is'.

Same problem with having "?" in the file name. I didn't check other characters.

**Comment by mpenkov** [comment]
Thank you for reporting this problem. I think the bug is in our S3 URL parsing code, somewhere in [this function](https://github.com/RaRe-Technologies/smart_open/blob/ce3d8acf7810358c93cbe11375dc48485901ccdf/smart_open/smart_open_lib.py#L650).

Are you able to make a PR?

**Comment by hexvolt** [comment]
No, it actually happens [before this function](https://github.com/RaRe-Technologies/smart_open/blob/ce3d8acf7810358c93cbe11375dc48485901ccdf/smart_open/smart_open_lib.py#L607) - that's the result the `urlsplit()` returns. It treats `folder/picture ` as the `path` and `1.jpg` as a `query`.

Which, from it's standpoint, is also kinda valid if you treat the S3 URL as a standard URL.

I can make a PR but need to know which way to fix it, ideologically:
a. Alter the URL parsing logic (special URL parsing for S3 specifically) and keep the same interface for the users
or
b. Require the users provide the so-called "quoted" values `s3://bucket-name/folder/picture%20%231.jpg` and unqote it to `picture #1.jpg` before sending to S3.

**Comment by mpenkov** [comment]
Which version of smart_open are you using? I cannot reproduce the problem using the most recent version.

The urlsplit code is behaving correctly, because we pass `allow_fragments=False` to it.

```python
In [7]: url
Out[7]: 's3://key/folder/image #1.jpg'

In [8]: urlsplit(url, allow_fragments=False)
Out[8]: SplitResult(scheme='s3', netloc='key', path='/folder/image #1.jpg', query='', fragment='')
```

**Comment by mpenkov** [comment]
I could only reproduce the problem with question mark (?) in the URL. We'll fix this in #291. Thanks again for letting us know.

**Comment by hexvolt** [comment]
Hm, yes you're right, just debugged this example again and # appeared to work ok. Maybe I mixed it up with `urlparse` in requests when I was trying to find a culprit and experimented with both `requests` and `smart_open`. So the issue is with question mark only indeed. Thanks for addressing this.

**Comment by kn000x** [comment]
Could you please check:
Temporarily replacing `?` with `\n` in `safe_urlsplit` is conflicting with the handling of `_UNSAFE_URL_BYTES_TO_REMOVE` within newer `urlsplit` versions:

https://github.com/python/cpython/commit/8a595744e696a0fb92dccc5d4e45da41571270a1#diff-b3712475a413ec972134c0260c8f1eb1deefb66184f740ef00c37b4487ef873e
