### ISSUE TITLE
How to open an audio file?

### ISSUE THREAD

**Issue by shoegazerstella** [RaRe-Technologies/smart_open#287]
Hello and thank you for this very useful tool!

It would be possible to use it for opening an audio file that is stored on s3?
I can't find the proper script for this. Thanks a lot.

**Comment by mpenkov** [comment]
You can open an audio file the same way you open any other file on S3. For examples, please see the README.rst file.

**Comment by shoegazerstella** [comment]
Sorry I did not include any code or errors. I am indeed trying something like:

```
with open('s3://mybucket/myprefix/audio.mp3', 'rb') as fin:
    print(fin)
    print(type(fin))
    y, sr = librosa.load(fin)
    print(sr)
    print(y)
```

```
<smart_open.s3.SeekableBufferedInputBase object at 0x1218c2b70>
<class 'smart_open.s3.SeekableBufferedInputBase'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-f436b8820887> in <module>
      3     print(fin)
      4     print(type(fin))
----> 5     y, sr = librosa.load(fin)
      6     print(sr)
      7     print(y)

/anaconda2/envs/audio36/lib/python3.6/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    110 
    111     y = []
--> 112     with audioread.audio_open(os.path.realpath(path)) as input_file:
    113         sr_native = input_file.samplerate
    114         n_channels = input_file.channels

/anaconda2/envs/audio36/lib/python3.6/posixpath.py in realpath(filename)
    385     """Return the canonical path of the specified filename, eliminating any
    386 symbolic links encountered in the path."""
--> 387     filename = os.fspath(filename)
    388     path, ok = _joinrealpath(filename[:0], filename, {})
    389     return abspath(path)

TypeError: expected str, bytes or os.PathLike object, not SeekableBufferedInputBase
```

And of course Librosa does not work as it expects a path-like object.
Do you have any advice on how to actually read that `smart_open.s3.SeekableBufferedInputBase` object as an audio?

Thanks a lot

**Comment by mpenkov** [comment]
This sound system like a question for the librosa devs.

**Comment by loretoparisi** [comment]
@mpenkov Is it possible to convert a `SeekableBufferedInputBase` to bytes?

**Comment by mpenkov** [comment]
Yes, just do `buffer.read()` from it.

**Comment by loretoparisi** [comment]
@mpenkov okay, thank you, so it seems that `audioread` does not support reading the bytes directly - https://github.com/beetbox/audioread/issues/92

**Comment by topplethepat** [comment]
This worked for me with an audio file:
with smart_open.open(stream_url, 'rb',buffering=0) as f:
