### ISSUE TITLE
No handlers could be found for logger "smart_open.ssh"

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/smart_open#288]
When importing the latest smart_open 1.8.1.

```python
In [1]: import smart_open
No handlers could be found for logger "smart_open.ssh"
```

This is a bug: the library should not be logging anything at import-time. Logging is not configured yet at that time, and cannot be configured even in principle: configuring logging is up to the user, not the library.

The culprit seems to be here, introduced in #267:
https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/ssh.py#L33

We should be using `warnings.warn` instead.

Also (unrelated): the module lists me as the author, but I don't remember writing any of this code.

**Comment by mpenkov** [comment]
> Also (unrelated): the module lists me as the author, but I don't remember writing any of this code.

Strictly speaking, the comment at the top of the file lists you as the _copyright owner_, as required by the [gensim contribution guidelines](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#legal) as opposed to the direct author of the code. If you like, I can add myself to the copyright statement to emphasize the joint copyright. The same thing goes for other modules.

Let me know how you'd like me to proceed with this.

**Comment by piskvorky** [comment]
You're right, my bad, sorry.

I have a *slight* preference for including code author(s) as well (in addition to the copyright) in the header. This makes contacting authors in the future easier. More relevant in Gensim than here, TBH. No big deal either way.
