### ISSUE TITLE
Is there a way to convert line to JSON?

### ISSUE THREAD

**Issue by amitdhawan** [RaRe-Technologies/smart_open#302]
Im new to python and found this library interesting to parse large csv files from S3. Im able to get the csv line using this library but now i need to convert thr csv line to json and send out  json line to other consumers.

I used below code to parse and make json from csv:-

```
def convert_csv_to_json(line):
    reader = csv.DictReader(io.StringIO(line))
    json_data = json.dumps(list(reader))
    return json_data

 for line in open('s3://' + s3_input_bucketname + '/' + s3_input_filepath):
                    # TODO parse the CSV
                    print(convert_csv_to_json(str(line)))
```

 print(convert_csv_to_json(str(line))) prints below lines in my csv file:-

```

"c0","ca","cb","cid","fontids","count"

"2018-12-20 19:00:00","js","e2823a34-e7a0-44fb-9cad-bad4ed1ed9d6",,,"1"

"2018-12-20 19:00:00","css","4980b5f2-4d09-4684-95b7-f29bcb72c238",,,"1"

"2018-12-20 19:00:00","css","e2823a34-e7a0-44fb-9cad-bad4ed1ed9d6",,,"1"

Note:-  c0, ca etc are my headers at the first line so my json would be like below:-

First json object can be like below:
{
  "c0": "2018-12-20 19:00:00",
   "ca": "js",
   "cb": "e2823a34-e7a0-44fb-9cad-bad4ed1ed9d6",
   "cid": "Null",
   "fontids": "Null",
   "count" : 1
}
```

Now the error i get is attached
<img width="971" alt="Screen Shot 2019-04-20 at 6 44 52 PM" src="https://user-images.githubusercontent.com/14885126/56457734-6611c780-639c-11e9-8587-ef041164c27e.png">

**Comment by mpenkov** [comment]
Thank you for your interest in the library, but this is the wrong place to ask your question, because it is not related to a bug or problem with the smart_open library. Please try somewhere like StackOverflow.

**Comment by amitdhawan** [comment]
@mpenkov thanks for your reply. Surely, i will ask on other platforms, but would you mind providing me some direction in to the solution. If not, then also its fine :-)
