### ISSUE TITLE
Checking for file existence.

### ISSUE THREAD

**Issue by luckydonald** [RaRe-Technologies/smart_open#303]
As we use s3 for storage of generated assets, and only generate them again if not existing yet, we need to implement a check for existence.

How about a `from smart_open import exists`?
It would be great if this library could also allow easy checking for existence, tailored for it's multiple backends.

```py
from smart_open import exists  # like os.exists
if not exists("s3://my_key:my_secret@my_server:my_port@my_bucket/some_file.mp4"):
  data = long_running_procedure("some_file.mp4")   # generate assets
  from smart_open import open
  with open("s3://my_key:my_secret@my_server:my_port@my_bucket/some_file.mp4", "wb") as f:
    f.write(data)
  # end with
  print("Generated from scratch.")
else:
  print("Already uploaded.")
# end if
```

**Comment by luckydonald** [comment]
For `boto3`, which is internally used by `smart_open` we used the listing with `Prefix=file_path` to check for existence, as it doesn't download the file.
```py
def exists(bucket_name, file_path):
    s3 = boto3.resource(
        's3',
        endpoint_url=f'{proto}://{host}:{port}',
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
    )
    # Bucket name we wanna use
    bucket = s3.Bucket(bucket_name)
    # list files matching a filter: the path
    objs = list(bucket.objects.filter(Prefix=file_path))
```
Source: [Stackoverflow](https://stackoverflow.com/a/55234136/3423324#check-if-a-key-exists-in-a-bucket-in-s3-using-boto3)

**Comment by mpenkov** [comment]
Why not just open the URL and see if that fails?

**Comment by luckydonald** [comment]
@mpenkov I don't wanna download it, just need to make sure that I don't waste resources to produce it twice.
Also I don't understand how that would look like, maybe you can show me a code example?

**Comment by mpenkov** [comment]
You don't need to download it. Smart_open **streams** its data. If you open a stream, but don't actually read from it, nothing gets downloaded.

Try:

```python
try:
    with smart_open.open('s3://bucket/key/does/not/exist.txt'):
        file_exists = True
except ValueError:
    file_exists = False
```

The ValueError gets raised [here](https://github.com/RaRe-Technologies/smart_open/blob/052ff93c110ab9e4ef94bd55667c9b6707d1ceee/smart_open/s3.py#L150) in case you want to do more precise checking.

**Comment by luckydonald** [comment]
@mpenkov shouldn't it raise an `IOError`?

**Comment by mpenkov** [comment]
I suppose IOError is more suitable. ValueError is there for historical reasons.

**Comment by luckydonald** [comment]
@mpenkov 
Being a "better" `open` I would expect similar or even same exception classes being used. 
Should I create an issue for that? Or you wanna do that?

**Comment by mpenkov** [comment]
Sure, you could make a new issue. A PR would be even better.

**Comment by luckydonald** [comment]
I don't feel comfortable editing this online, as I don't have the code cloned locally, and therefore have no unit test setup.

**Comment by a3linux** [comment]
I got NoSuchKey error when I tried s3 object does not exist and FileNotFoundError for does not exist local file.

**Comment by ciurlaro42** [comment]
> Using `boto3`, which also is internally used by `smart_open`, we used the listing with `Prefix=file_path` to check for existence, as it doesn't download the file, and we have the `s3:ListBucket` permission set anyway.
> 
> ```python
> def exists(bucket_name, file_path):
>     s3 = boto3.resource(
>         's3',
>         endpoint_url=f'{proto}://{host}:{port}',
>         aws_access_key_id=access_key,
>         aws_secret_access_key=secret_key,
>     )
>     # Bucket name we wanna use
>     bucket = s3.Bucket(bucket_name)
>     # list files matching a filter: the path
>     objs = list(bucket.objects.filter(Prefix=file_path))
>     return len(objs) > 0
> # end def 
> ```
> 
> Source: [Stackoverflow](https://stackoverflow.com/a/55234136/3423324#check-if-a-key-exists-in-a-bucket-in-s3-using-boto3), also includes other solutions with probably don't require `s3:ListBucket`.

I don't understand why this is not built in the library
