### ISSUE TITLE
transport_params: default value for keyword argument is mutable

### ISSUE THREAD

**Issue by luckydonald** [RaRe-Technologies/smart_open#304]
For some reason, `transport_params.session` defaults to something I didn't set, causing it to ignore the arguments set via url.

Here is my code:
```py
with open('s3://ACCESS_TOKEN:ACCESS_SECRET@s3.example.com:443@bucketname/some_file.mp4', 'wb') as s3_file:
    # code
# end with
```
The logs:
```
"2019-04-22T10:55:45.340767000Z DEBUG"    smart_open.smart_open_lib.open: {'transport_params': {'session': Session(region_name=None)}, 'ignore_ext': False, 'opener': None, 'closefd': True, 'newline': None, 'errors': None, 'encoding': None, 'buffering': -1, 'mode': 'wb', 'uri': 's3://ACCESS_TOKEN:ACCESS_SECRET@s3.example.com:443@bucketname/some_file.mp4'}
"2019-04-22T10:55:45.341045000Z DEBUG"    smart_open.smart_open_lib._s3_open_uri: s3_open_uri: {'transport_params': {'session': Session(region_name=None)}, 'mode': 'wb', 'parsed_uri': Uri(scheme='s3', uri_path=None, bucket_id='bucketname', key_id='some_file.mp4', port=443, host='s3.example.com', ordinary_calling_format=True, access_id='ACCESS_TOKEN', access_secret='ACCESS_SECRET', user=None)}
"2019-04-22T10:55:45.341139000Z WARNING"  smart_open.smart_open_lib._s3_open_uri: ignoring credentials parsed from URL because they conflict with transport_params.session. Set transport_params.session to None to suppress this warning.
```

It shouldn't have any session though, and just use the url params.

**Comment by luckydonald** [comment]
My guess is, that the problem is that the default value of `transport_params` is mutable.
Having `transport_params=dict()`, Pycharm helpfully notes:
<img width="396" alt="Screenshot 2019-04-22 at 13 25 14" src="https://user-images.githubusercontent.com/2737108/56498544-73e15d00-6502-11e9-9c1f-3d2ce781c155.png">
> **Default argument is mutable**
> This inspection detects when a mutable value as list or dictionary is detected in a default value for an argument. Default argument values are evaluated only once at function definition time, which means that modifying the default value of the argument will affect all subsequent calls of the function.

This means, if you modify _anything_ inside this `transport_params` dict, _anywhere_ down the road, it will update the value of the keyword default `open(transport_params=dict())` argument, which could cause this issue.

So the solution would be 
```py
def open(..., default_value=None):
  if default_value is None:
    default_value = dict()
  # end if
  # ...  
# end def 
```

If it is needed to allow the user to set `None` instead of the default, you can use the following approach:
```py
class DEFAULT(object): pass

def open(..., default_value=DEFAULT):
  if default_value == DEFAULT:
    default_value = dict()
  # end if
  # ...   
# end def
```

**Comment by mpenkov** [comment]
Can you please post a code sample that demonstrates how the existing code breaks?

**Comment by mpenkov** [comment]
Thank you for reporting this. I'll have a look into it.

**Comment by luckydonald** [comment]
The param `=dict()` to be happening at several places.

**Comment by luckydonald** [comment]
Here is an short example illustrating the effect:
```py
def example(foo=dict()):
    print("Param foo: " + repr(foo))
    foo['something'] = 4458
# end def
```
```py
>>> example()
Param foo: {}
>>> example()
Param foo: {'something': 4458}
```

**Comment by luckydonald** [comment]
So basically the reproduction you asked about and deleted would be using `smart_open.open` twice.
