### ISSUE TITLE
Custom S3 host is ignored when using the url format.

### ISSUE THREAD

**Issue by luckydonald** [RaRe-Technologies/smart_open#305]
https://github.com/RaRe-Technologies/smart_open/blob/052ff93c110ab9e4ef94bd55667c9b6707d1ceee/smart_open/smart_open_lib.py#L589-L593
This is missing something like `endpoint_url`:
```py
transport_params['session'] = boto3.Session(
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        endpoint_url='{proto}://{host}:{port}'.format(proto="https", host="s3.example.com" port=443),
)
```
<br><br>

---------
Maybe you could add integrations checks against a self hosted instance.
Minio is quite easy to set up:  [Quick start guide](https://docs.min.io/docs/minio-quickstart-guide.html).
Also they have a public running demo instance at [play.min.io](https://play.min.io). That probably could be used too.

**Comment by luckydonald** [comment]
The ugly workarround is the following:
```py
with open(f's3://{access_key}:{secret_key}@{host}:{port}@{path}', 'wb', transport_params=dict(session=boto3.Session(aws_access_key_id=access_key,aws_secret_access_key=secret_key,),resource_kwargs=dict(endpoint_url=f'{proto}://{host}:{port}',),) as f:
       f.write('FOOBAR');
# end with
```

**Comment by mpenkov** [comment]
Thanks for reporting this. I will look into it.

**Comment by luckydonald** [comment]
Here is a full example leveraging the play.min.io demo:

```py
with open('s3://Q3AM3UQ867SPQQA43P2F:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG@play.min.io:9000@smart-open-example/test.txt', "w"):
    s3_file.write('See, it isn\'t working :(')
# end with
```

**Comment by luckydonald** [comment]
Sweet.
