### ISSUE TITLE
Failed file access should raise IOError not ValueError (S3)

### ISSUE THREAD

**Issue by luckydonald** [RaRe-Technologies/smart_open#306]
See https://github.com/RaRe-Technologies/smart_open/issues/303#issuecomment-485426630 for details.

I recognise this to be a breaking change (Unless you make a subclass extending both Exception classes) so proper semantic verion should be assigned.

**Comment by luckydonald** [comment]
Maybe while working on this, the original error could made available as parameter, so it isn't swallowed.

**Comment by luckydonald** [comment]
To keep code compatible maybe we can make a exception subclass of both?

```py
class SmartOpenOpenError(ValueError, IOError): pass
raise SmartOpenOpenError(...)
```

```should make it compatible with both
    try:
        with open(s3_url, "r", transport_params=transport_params):
            pass  # just check if exists.
        # end with
        return redirect(http_url)
    except IOError:
        logger.info(f'File {file} does not exist yet.')  # we just continue above
    # end def
```
and old code expecting `ValueError`.

**Comment by piskvorky** [comment]
@mpenkov did #325 really fix this? It seems unrelated to me.

**Comment by mpenkov** [comment]
Yes, [here](https://github.com/RaRe-Technologies/smart_open/pull/325/files#diff-6d8b12a1a0fab36149bf68fc0ef770faR146) is the relevant part.
