### ISSUE TITLE
Question - Upload using Django and stream to S3

### ISSUE THREAD

**Issue by ubswrk** [RaRe-Technologies/smart_open#313]
Hi,
I'd be happy to hear your recommendations for the simple use case of exposing an endpoint to upload a file to S3. So basically the use case is as follows:
1. User uploads a ~500MB (zipped) file through a web browser 
2. Django web server handles the request and pushes the file to S3

I'm currently looking at MultiPartParser, and if I understand this correctly Django will save the file 
to a local tmp directory, and then I'll have to read it (with smart_open) in order to upload it to S3.
Is there a way to stream the file directly from the request to S3 to avoid saving it locally?
Thanks!

**Comment by mpenkov** [comment]
Sorry, this is more of a Django question than a smart_open question.

smart_open will stream anything you give it, in theory. So provided you have access to the incomplete upload stream, you should be able to write it to S3 as it comes in.
