### ISSUE TITLE
EOFError: End of stream already reached

### ISSUE THREAD

**Issue by antikvarBE** [RaRe-Technologies/smart_open#320]
Hello,

I'm currently running into a streaming issue using smart_open with tarfiles.
I've described this issue on StackOverflow https://stackoverflow.com/questions/56310366/getting-a-eoferror-end-of-stream-already-reached-error-when-trying-to-untar-a

Any clues?
Thank you in advance.

**Comment by piskvorky** [comment]
`.tbz` is not a recognized compression extension by `smart_open` (though if it's just `.bz2`, you could [register it yourself](https://github.com/RaRe-Technologies/smart_open#supported-compression-formats)).

I'm puzzled by your "The code I provide here works fine for small files." – I don't see how it could work. @mpenkov any ideas?

**Comment by antikvarBE** [comment]
Hi @piskvorky,
Thanks for a prompt reaction.

I just tried to run in with the local copy of the file as you suggested and the situation remains the same: OK for small files but NOK for larger ones.

---

As of your previous suggestion, I did try to register my own compressors.
First I just did:
```
def _handle_tbz(file_obj, mode):
    return bz2.BZ2File(filename=file_obj, mode=mode)
```
which worked fine but was providing me with pure tar files.
So I tried this:
```
def _handle_tar(file_obj, mode):
    return tarfile.open(fileobj=file_obj, mode='r|bz2')
```
and got the following error:
```
AttributeError: 'TarFile' object has no attribute 'read'
```
From tarfile documentation, I understood that you need to apply one more step to the TarFile object that's being returned either extractfile(), extractall(), etc. So this is why I tried the code you saw on StackOverflow:
```
with tf.extractfile(tf.next()) as tfext:
    for line in tfext:
        fout.write(line)
```
And this works fine... for small files only. With larger files, I can only process the very first fraction of the file and then it says:
```
Traceback (most recent call last):
  File "./script.py", line 31, in <module>
    download_file(fileName)
  File "./script.py", line 25, in download_file
    for line in tfext:
  File "/.../lib/python3.7/tarfile.py", line 706, in readinto
    buf = self.read(len(b))
  File "/.../lib/python3.7/tarfile.py", line 695, in read
    b = self.fileobj.read(length)
  File "/.../lib/python3.7/tarfile.py", line 537, in read
    buf = self._read(size)
  File "/.../lib/python3.7/tarfile.py", line 554, in _read
    buf = self.cmp.decompress(buf)
EOFError: End of stream already reached
```
Thanks again for all the help!

**Comment by mpenkov** [comment]
Thank you for the bug report. I had a look on StackOverflow, and can see you provided some example source there. Could you simplify it by removing the code that does the writing, and post the source here? Ideally, it'd be something we can just copy-paste into an interpreter and reproduce your problem. It'd be super awesome if you used public data as well, but I can see how that may be difficult.

The reason I ask is that it makes your problem simpler for us to reproduce.

As an aside, It appears to me that the reading and the writing are unrelated in this problem - it'd be good if you could verify that.

**Comment by antikvarBE** [comment]
Hi @mpenkov,

Thank you for looking into it with me. It's highly appreciated.
I guess you can just use any .tbz (tar with bz2 compression algorithm) file that's relatively large ( around 8Mb should do) to run a test on the following code:
```
from smart_open import open, register_compressor
import tarfile


filesToDownload = ['name_of_local_tbz_file']


def _handle_tbz(file_obj, mode):
    return tarfile.open(fileobj=file_obj, mode='r|bz2')


register_compressor('.tbz', _handle_tbz)


def download_file(fileName):
    fileUrl = fileName
    with open(fileUrl) as fin:
        destination = fileName + '.csv'
        with open(destination, 'wb') as fout:
            with fin.extractfile(fin.next()) as tfext:
                for line in tfext:
                    fout.write(line)


for fileName in filesToDownload:
    download_file(fileName)
```
A quick sidenote:
You'll notice that I'm not using the "mode" parameter when I'm registering a new compressor as the string "r|bz2" when passed as a parameter to smart_open.open() command throws an error about an unsupported mode specification. I guess you compare strings at opening and, obviously, "r|bz2" doesn't make any sense for any compressor you're currently supporting.

**Comment by mpenkov** [comment]
I tried running your source under Py3.6.5 and got the following error:

```(smart_open) misha@cabron:~/git/smart_open$ python bug.py
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    download_file(fileName)
  File "bug.py", line 20, in download_file
    with fin.extractfile(fin.next()) as tfext:
AttributeError: __enter__
```

Which version of Python are you using?

**Comment by antikvarBE** [comment]
I’m using python 3.7

**Comment by mpenkov** [comment]
I get the same problem with 3.7. Could you please double-check your example?

```
(so37) misha@cabron:~/git/smart_open$ python --version
Python 3.7.3
(so37) misha@cabron:~/git/smart_open$ cat bug.py 
from smart_open import open, register_compressor
import tarfile


filesToDownload = ['dummy']


def _handle_tbz(file_obj, mode):
    return tarfile.open(fileobj=file_obj, mode='r|bz2')


register_compressor('.tbz', _handle_tbz)


def download_file(fileName):
    fileUrl = fileName + '.tbz'
    with open(fileUrl) as fin:
        destination = fileName + '.csv'
        with open(destination, 'wb') as fout:
            with fin.extractfile(fin.next()) as tfext:
                for line in tfext:
                    fout.write(line)


for fileName in filesToDownload:
    download_file(fileName)

(so37) misha@cabron:~/git/smart_open$ python bug.py 
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    download_file(fileName)
  File "bug.py", line 20, in download_file
    with fin.extractfile(fin.next()) as tfext:
AttributeError: __enter__
```

**Comment by antikvarBE** [comment]
Strange. I never had this particular issue before. Here's a file I'm trying to process (unfortunately, given the limitations of GitHub, I had to zip it first. If you unzip it you should have the real thing):

[mix_collection.tbz.zip](https://github.com/RaRe-Technologies/smart_open/files/3222005/mix_collection.tbz.zip)

**Comment by mpenkov** [comment]
OK, I can reproduce your problem.

I can also simplify the example further:

```python
import io
import tarfile
import sys


def download_file(file_path, use_smart_open=False):
    destination = file_path + '.csv'

    if use_smart_open:
        from smart_open import open
    else:
        from io import open

    with open(file_path, mode='rb') as file_obj:
        with tarfile.open(fileobj=file_obj, mode='r|bz2') as fin:
            with io.open(destination, 'wb') as fout:
                with fin.extractfile(fin.next()) as tfext:
                    for line in tfext:
                        fout.write(line)

download_file(sys.argv[1])
```

Interestingly, I get the same result regardless of whether I'm using smart_open.open or io.open. This leads me to suspect the problem isn't actually in smart_open.

**Comment by antikvarBE** [comment]
Right, I guess people who work on [https://github.com/python/cpython/blob/master/Lib/tarfile.py](url) might cast some light on the issue. I just don't see where one can submit an issue or link to an existing one on this page.

**Comment by mpenkov** [comment]
You may want to consider using the Python bug tracker, because tarfile is in the standard library.

https://bugs.python.org/

Use the search feature to find tarfile-related issues, there may already be something related there.
