### ISSUE TITLE
s3 open fails while s3.upload_fileobj works ok

### ISSUE THREAD

**Issue by ubswrk** [RaRe-Technologies/smart_open#326]
Hi,
Any idea why 
`with open(s3_file_path, 'wb', transport_params=transport_params) as fout:` returns 
`FileNotFoundError: [Errno 2] No such file or directory: <s3_file_path>`,
while `s3.upload_fileobj(bucket, s3_file_path)` works with no errors?
(all directories in the path exist in the bucket)
Thanks!
(1.8.3)
Udi

**Comment by piskvorky** [comment]
Please post the full stack trace.

**Comment by ubswrk** [comment]
found the issue - it was a missing s3:// prefix.
thanks.
