### ISSUE TITLE
Error while reading ▒ (MEDIUM SHADE) characters from CSV. 

### ISSUE THREAD

**Issue by amolsaudar123** [RaRe-Technologies/smart_open#327]
Hi Folks,

I'm trying to upload CSV from HDFS to S3 due to special character  ▒ (MEDIUM SHADE) in csv,  smart_open fails to upload file to s3 and here is the screen shot.

And kindly let me know if you are having solution for this.

![c1](https://user-images.githubusercontent.com/29245705/59854929-80aeef80-9391-11e9-87b2-f645955464ec.PNG)

Thanks in advance.

**Comment by piskvorky** [comment]
Your screenshot says `Access denied`. What makes you think it has anything to do with `▒`?

**Comment by mpenkov** [comment]
Closing as inactive.
