### ISSUE TITLE
support getting endpoint_url from os.environ

### ISSUE THREAD

**Issue by cailiang9** [RaRe-Technologies/smart_open#328]
https://github.com/RaRe-Technologies/smart_open/blob/aea05d090f5ced7980229b147ac86a42a45bc87d/smart_open/smart_open_lib.py#L65

**Comment by mpenkov** [comment]
There are already multiple methods of setting this (e.g. via keyword arguments and boto3 configuration). Why do we need yet another method?

**Comment by mpenkov** [comment]
@cailiang9 Are you able to set the S3 host via other methods?

**Comment by mpenkov** [comment]
@cailiang9 Ping
