### ISSUE TITLE
support http when port is not 443

### ISSUE THREAD

**Issue by cailiang9** [RaRe-Technologies/smart_open#329]
https://github.com/RaRe-Technologies/smart_open/blob/aea05d090f5ced7980229b147ac86a42a45bc87d/smart_open/smart_open_lib.py#L624

**Comment by mpenkov** [comment]
Could you please be more descriptive in your tickets?

What are you trying to achieve? Why? What have you tried? Sample code would be good.

**Comment by cailiang9** [comment]
my endpoint_url is 'http://host:port' not https, through uri: s3://host:port@bucket/ , it is not possible to use http protocol.

**Comment by mpenkov** [comment]
Please show your sample source code, including your actual S3 URI (you can redact private information as needed).

I think it should be possible to access your URI by specifying the right keyword parameters, e.g. see this example in README.md:

```python
# Stream to Digital Ocean Spaces bucket providing credentials from boto profile
transport_params = {
    'session': boto3.Session(profile_name='digitalocean'),
    'resource_kwargs': {
        'endpoint_url': 'https://ams3.digitaloceanspaces.com',
    }
}
with open('s3://bucket/key.txt', 'wb', transport_params=transport_params) as fout:
    fout.write(b'here we stand')
```

**Comment by mpenkov** [comment]
@cailiang9 Did this solve your problem?
