### ISSUE TITLE
Implement seek over HTTPS

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#331]
```python
with smart_open.open("https://cs.nyu.edu/~roweis/data/nips12raw_str602.tgz", "rb") as fin:
    fin.seek(0)
```

raises "UnsupportedOperation: seek"

smart_open 1.8.3

**Comment by piskvorky** [comment]
How could we support seek over gzip? Sounds very tricky.

**Comment by mpenkov** [comment]
We're not actually seeking over gzip. The above code is seeking over raw bytes.

**Comment by piskvorky** [comment]
Aha. We don't recognize `.tgz` as a compressed format? (shorthand for `.tar.gz`)

Not sure if `seek` over http(s) is implemented (apparently not), but definitely a desirable feature.

**Comment by mpenkov** [comment]
Yes, we don't.

I'll reword the ticket as a feature request, that way someone may feel more inclined to act on it.
