### ISSUE TITLE
Help creating a zip from bucket

### ISSUE THREAD

**Issue by Jonyorker** [RaRe-Technologies/smart_open#335]
Hi,

New to python, and I am having a hard time understanding how I could create a zip file from Bucket/Prefix?

I would use .s3_iter_bucket but after that I'm at a loss as to what to do to create a zip.

Thanks!

**Comment by mpenkov** [comment]
Sorry, this isn't the appropriate place to ask for such help. Please try somewhere like StackOverflow.
