### ISSUE TITLE
s3_iter_bucket works but open fails "file not found"

### ISSUE THREAD

**Issue by Jonyorker** [RaRe-Technologies/smart_open#336]
I am having some troubles with "open" but "s3_iter_bucket" works well.

When I run the s3_iter_bucket('test-bucket', prefix='test/1/') it works well

however, 

for line in open('s3://test-bucket/test/1/file1.iso'):
    print(line) 

returns error "file not found"

Why would that be?

**Comment by piskvorky** [comment]
Full stack trace + log at DEBUG level please.

**Comment by mpenkov** [comment]
@Jonyorker Could you please provide more info? Otherwise, we cannot help you and will have to close this ticket.
