### ISSUE TITLE
Code snippets of smart_open improvements

### ISSUE THREAD

**Issue by tmylk** [RaRe-Technologies/smart_open#34]
@ziky90 What are examples when smart_open comes in handy for HDFS and WebHDFS?

Someone invited me to talk about smart_open for 20 minutes. I have created the code comparisons for S3 below. Would like to expand them to other filesystems. What pains had smart_open solved for you in HDFS or WebHDFS?

![multipart](https://cloud.githubusercontent.com/assets/1261528/10450853/cf751d10-7194-11e5-8d2f-3475d0afff61.png)
![from_s3_to_memory](https://cloud.githubusercontent.com/assets/1261528/10450880/f019f36a-7194-11e5-81f6-8f014068bff8.png)

**Comment by ziky90** [comment]
The main reason of HDFS and WebHDFS for us is that we have data in different systems (FTP servers, S3, HDFS, locally) and by implementing WebHDFS we can easily switch just path when data are moved for example from S3 to HDFS.

Another reason was that I was used to use smart_open from my previous work.

Also you can write much shorter code. For WebHDFS you would have to do it via requests library, but here it's just few lines.
