### ISSUE TITLE
 cannot import name 'open' from 'smart_open'

### ISSUE THREAD

**Issue by mirfan899** [RaRe-Technologies/smart_open#343]
Gensim not working properly after updating to the latest version. Getting following error
```shell
ImportError: cannot import name 'open' from 'smart_open' (/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/smart_open/__init__.py)
```
I'm using Python 3.7 and Gensim 3.8.0

**Comment by piskvorky** [comment]
What's your version of `smart_open`?

**Comment by mirfan899** [comment]
my bad, after updating the `smart_open` issue is gone. But I think when someone updates the `gensim`, it's dependencies should be updated.

**Comment by piskvorky** [comment]
Yeah, it should. @mpenkov if we require a specific version of smart_open for Gensim to work, can we pin that in `setup.py`?

**Comment by mpenkov** [comment]
@piskvorky I will update the pin. It's currently >= 1.7.0, should be >= 1.8.1.

**Comment by mpenkov** [comment]
Done here: https://github.com/RaRe-Technologies/gensim/commit/f2ad5c2d7465e3ee1ee803c8f45faa81ac3f4472#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by lijunchen22** [comment]
can anyone know how to solve this issue？

D:\python\python.exe E:/python_app/sim_db.py
unable to import 'smart_open.gcs', disabling that module
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\815km\AppData\Local\Temp\jieba.cache
Loading model cost 0.681 seconds.
Prefix dict has been built successfully.
