### ISSUE TITLE
S3 BufferedInputBase fills buffer during every read

### ISSUE THREAD

**Issue by terencezl** [RaRe-Technologies/smart_open#348]
Here is a question about the purpose of buffering in the Input file class `BufferedInputBase`. Assuming buffer helps small amount of reads, and loads from S3 remote end less frequently than the reads from caller, the current implementation doesn't achieve the purpose.

https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/s3.py#L284

If the request to read is consistently small, the buffer has to be filled at all times. Wouldn't it be nice to fill to a prefilled buffer size (new param) first?

On the other hand, with `BufferOutputBase`, it behaves properly, only uploading to S3 when many writes reach a certain threshold.

https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/s3.py#L521

**Comment by mpenkov** [comment]
I think we should just fill it to `io.DEFAULT_BUFFER_SIZE` or similar constant, unless `size` is larger. What do you think?

**Comment by terencezl** [comment]
That should certainly work.

**Comment by mpenkov** [comment]
Are you able to make a PR?
