### ISSUE TITLE
Using a proxy to access S3

### ISSUE THREAD

**Issue by asieira** [RaRe-Technologies/smart_open#35]
The boto S3 connection allows `proxy`, `proxy_port`, `proxy_user` and `proxy_pass` to be set explicitly. It would be nice to have a way to propagate those options from `smart_open` to the opening of the connection.

Maybe the best way to go about this is to allow the boto connection object to be passed to `smart_open`, instead of a new one being created each time.

**Comment by piskvorky** [comment]
Hmm, couldn't we do this using by extending the functionality added in #30 ?

**Comment by asieira** [comment]
Not sure if I understand what you have in mind, but I don't think we can use the same argument here. 

On S3OpenWrite, the current usage for `**kw` is to pass it along to `initiate_multipart_upload`, not `connect_s3`: https://github.com/piskvorky/smart_open/blob/master/smart_open/smart_open_lib.py#L402

We could, however, add a new argument to `smart_open` that is a dict with keyword arguments to be passed along to `connect_s3` in a similar way.

**Comment by asieira** [comment]
Ok, I though of something simpler. How about `smart_open` properly handles the case where `uri` is actually an instance of `boto.s3.key.Key` and uses its data instead of creating new connection and bucket objects?

**Comment by piskvorky** [comment]
Hmm, interesting idea. As long as it's backward compatible (strings work the same way), we could "add" support for other types of input, why not.

Any comments @ziky90 @VincTheSecond ?

**Comment by ziky90** [comment]
I like the idea. It would be useful for me as well to be able to use `proxy` parameter.

**Comment by asieira** [comment]
The challenge is that for this to work, I would change the constructors for both `S3OpenRead` and `S3OpenWrite` to receive a `boto.s3.key.Key` instance, which would not be strictly backwards compatible if anyone was using them directly.

**Comment by asieira** [comment]
I just submitted a pull request with a working version of this idea. I'll still need some help fixing one of the tests, which I temporarily commented out.

**Comment by tmylk** [comment]
Merged in #38
