### ISSUE TITLE
ignoring unsupported keyword arguments: ['version_id']

### ISSUE THREAD

**Issue by pederpansen** [RaRe-Technologies/smart_open#351]
Hi,

I'm getting the above error when trying to open a specific file version from S3:

```
with smart_open.open(s3_url, transport_params={'version_id': s3_version}) as fin:
```

I'm using the latest release 1.8.4 installed via pip.

**Comment by mpenkov** [comment]
I cannot reproduce your problem here.

What do you see if you run the code below through a repl?

```
(smartopen) sergeyich:gensim misha$ ipython
Python 3.6.5 (default, Mar 30 2018, 06:41:53)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from smart_open import open

In [2]: bucket, key = 'smart-open-versioned', 'demo.txt'

In [3]: version = 'KiQpZPsKI5Dm2oJZy_RzskTOtl2snjBg'

In [4]: with open('s3://%s/%s' % (bucket, key), transport_params={'version_id': version}) as fin:
   ...:     print(fin.read())
   ...:
second version


In [5]: import smart_open

In [6]: smart_open.__version__
Out[6]: '1.8.4'
```

**Comment by pederpansen** [comment]
This is really strange... in IPython, I get the same output as you. From my script, it gives my the above error message. I double-checked, the environment and `smart_open` package versions are identical.

**Comment by pederpansen** [comment]
I think I found a hint, although it doesn't make much sense to me. If I configure logging in my script, I see the mentioned error.

Here is a minimal example:

```
import logging
import smart_open

logging.basicConfig(format='%(asctime)s - %(message)s', level=logging.INFO)

bucket, key = 'smart-open-versioned', 'demo.txt'
print(smart_open.__version__)
with smart_open.open('s3://%s/%s' % (bucket, key), transport_params={'version_id': 'KiQpZPsKI5Dm2oJZy_RzskTOtl2snjBg'}) as fin:
    i = 0
    print(fin.read())
```

**Comment by pederpansen** [comment]
I believe the latest version of PyPi is from June 2nd (https://pypi.org/project/smart-open/), is it possible the version functionality was added afterwards and just wasn't released?

**Comment by mpenkov** [comment]
Ah, you're right, the release notes for 1.8.4 don't mention anything about version_id, so I think that feature is still unreleased at the moment.

We'll do another release soon.
