### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by fferegrino** [RaRe-Technologies/smart_open#352]
Trying not to be annoying here:

Is there a planned release soon? I can't seem to find any docs regarding the release strategy of `smart_open`.

Thanks for the package, and again, I hope not to sound demanding or annoying.

**Comment by mpenkov** [comment]
Hey @fferegrino, no problem. I'll try to release a new version next week or so, been a bit busy with `gensim` lately.

**Comment by fferegrino** [comment]
Nice! thank you.
