### ISSUE TITLE
ImportError: cannot import name open

### ISSUE THREAD

**Issue by JaharshKotha** [RaRe-Technologies/smart_open#354]
Trying this library to stream a huge file from s3 line by line

sample code : 

'''
from smart_open import open

for line in open('s3://test_bucket/test_folder/test_dump.json'):
    print(repr(line))
    break
'''

**Comment by piskvorky** [comment]
What version of `smart_open` are you using?

**Comment by JaharshKotha** [comment]
Version: 1.8.4

**Comment by piskvorky** [comment]
Yeah, that's the latest. @mpenkov any idea what could be wrong?

**Comment by mpenkov** [comment]
I cannot reproduce the problem here:

```
$ python
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smart_open
>>> smart_open.__version__
'1.8.4'
>>> from smart_open import open
>>> open
<function open at 0x7fd59f1ea378>
>>> 
```

@JaharshKotha Are you sure about the version? Can you try running the code above, and let me know what the output is?

**Comment by JaharshKotha** [comment]
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smart_open
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "smart_open.py", line 1, in <module>
    from smart_open import opeen
ImportError: cannot import name opeen

**Comment by mpenkov** [comment]
Well, the function is called `open`, not `opeen`, so there's your problem :)

**Comment by JaharshKotha** [comment]
I am importing it as from smart_open import opeen

**Comment by piskvorky** [comment]
That's incorrect, closing.
