### ISSUE TITLE
Add support for scp(ssh) protocol

### ISSUE THREAD

**Issue by val314159** [RaRe-Technologies/smart_open#36]
This would be pretty useful to copy from generic shell accounts to S3 and vice versa.

**Comment by piskvorky** [comment]
Yes, I can see how that is useful.

Python's [fabric](https://github.com/fabric/fabric) library has good support for this kind of thing; perhaps we could build on top of that?

Are you up for a pull request @val314159 ?

**Comment by val314159** [comment]
Yeah, i hadn't thought of the exact mechanism, I figured the most dead simple way would be just to shell out a command.  

fabric might be overkill, there's also this: https://pypi.python.org/pypi/scpclient 
They're both front ends to the paramiko library.

Let me play around and see what I can do - it should be fairly straightforward.

**Comment by piskvorky** [comment]
Perfect -- the simpler the dependencies, the better!

Thanks for offering the exploration / help. Feel free to open a PR for review once you have something reviewable.

**Comment by ziky90** [comment]
This is a good idea and it would remove my need of issue #33 which I was about to implement.
