### ISSUE TITLE
S3 Multipart upload using threads

### ISSUE THREAD

**Issue by vryazanov** [RaRe-Technologies/smart_open#363]
Hi there,
It would be great to have an ability to upload chunks to s3 with `ThreadPoolExecutor`, in other words to send each chunk in a separate thread to make uploading faster. This is how we do in my current project. I think it's better to include this functionality to `smart_open`. wdyt? let me know if it's interesting and I'll prepare a pull request.

**Comment by piskvorky** [comment]
Isn't uploading already I/O bound? How would more threads (more CPU) help?

**Comment by vryazanov** [comment]
@piskvorky in current implementation if we have 10 chunks to upload , they will be uploaded in a row. but since it's I/O bound operation we could do it in parallel in threads.
summarizing, the problem is that uploading a chunk is a blocking operation.

**Comment by piskvorky** [comment]
But threads won't help you in I/O bounds operations. They add more CPU, which is not the bottleneck.

I appreciate your offer, but as part of your PR, we'd need to see convincing benchmarks first. Can you post some numbers?

Threads always add a lot of complexity and maintenance and support headache, so unless the gains are obvious, I'm -1 on complicating the code.

**Comment by vryazanov** [comment]
@piskvorky ok, I got your point. I'll prepare some numbers first

**Comment by vryazanov** [comment]
Look at https://gist.github.com/vryazanov/10fc4f7790b56560565e13ad45a70e38
I tried to upload 1Gb file from my pc both ways (with and without threads), see results:
```
[vryazanov@localhost ~]$ time python3 benchmarks.py ./1GB.csv test-bucket 1Gb_threads.csv

real    2m22.517s
user    0m24.159s
sys     0m9.746s

[vryazanov@localhost ~]$ time python3 benchmarks.py ./1GB.csv test-bucket 1Gb.csv --simple
real    2m52.000s
user    0m12.583s
sys     0m6.046s
```

Thread pool gives me up to 30% in speed, but I didn't run a script a dozen of times to see more statistically correct results.
