### ISSUE TITLE
Is it possible to stream upload to a same file from multiple machines?

### ISSUE THREAD

**Issue by jk5462** [RaRe-Technologies/smart_open#364]
Hi,

I am attempting to make a program on AWS Lambda that needs to write a new S3 object. 

The problem is, the task can take beyond Lambda's current time limit of 15 minute run time. Right now, I am attempting to bypass this issue by invoking another Lambda and continuing the task.

I am aware that S3 does NOT support append operations to the existing objects, so I couldn't solve my problem by simply making the successor append to the object that the predecessor created.

Is there a way in which I can transfer the fileobj created by smart_open.open() to another machine? If possible, this will allow me to continue to write on a single object by iterating multiple lambda invokes.

I know this does not sound like a smart solution (especially considering that smart_open prob requires a connection through boto3 + other memory management issue...), and should probably go with Fargate, but I do not wish to use fargate.

**Comment by jk5462** [comment]
> What makes you think you cannot append to S3 objects? You can open, seek to the end, and continue writing.

Wait so.. I simply open an existing S3 object in WB mode, seek to its end, and continue writing data on to it and it will just append to the existing data? instead of overwriting it?

**Comment by jk5462** [comment]
Sorry for asking a dumb question. Could I get a sample code of your idea? Quite new to using boto3 and smart_open

**Comment by jk5462** [comment]
@mpenkov Hey, I was looking through the code and noticed this.

`if mode == READ_BINARY:
        fileobj = SeekableBufferedInputBase(
            bucket_id,
            key_id,
            version_id=version_id,
            buffer_size=buffer_size,
            session=session,
            resource_kwargs=resource_kwargs,
        )
    elif mode == WRITE_BINARY:
        fileobj = BufferedOutputBase(
            bucket_id,
            key_id,
            min_part_size=min_part_size,
            session=session,
            multipart_upload_kwargs=multipart_upload_kwargs,
            resource_kwargs=resource_kwargs,
        )
    else:
        assert False, 'unexpected mode: %r' % mode
    return fileobj`

It seems like WB mode is not seekable. Should I open two instances of RB and WB?..

**Comment by mpenkov** [comment]
Oh, I see. If we don't support seeking on the write stream, then yes, you cannot append.

Is seeking and writing to S3 possible in theory? I can't think of a reason why it wouldn't be.

**Comment by piskvorky** [comment]
AFAIK, the only way to stream to S3 is using multipart uploads (which smart_open already does).

**Comment by mpenkov** [comment]
The solution here is:

1. Get your lambda functions to write to some temporary location on S3 (using smart_open)
2. Once the lambda functions finish running, concatenate the temporary locations together (either by using smart_open or boto3 directly)
