### ISSUE TITLE
S3 integration tests not cleaning up after themselves

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#376]
We have a ton of S3 buckets under our account. They don't contain much data, but they eat up our quota (we're unable to create more than a certain number). We should work out why the tests are leaving these buckets in place as opposed to removing them after test completion.

**Comment by piskvorky** [comment]
Oh dear. Which bucket / account is that? I'll check the S3 bill.

**Comment by piskvorky** [comment]
AWS bill is still minimal, no problem there :+1:

**Comment by mpenkov** [comment]
Yeah, we pay for the volume of storage, not the number of buckets, so it's not a big deal cost-wise. Just a PITA.
