### ISSUE TITLE
s3 multpart upload doesn't complete correctly

### ISSUE THREAD

**Issue by vmaksimenko** [RaRe-Technologies/smart_open#381]
#### Problem description
in the heavily concurrent environment, it was noticed that our process leaves a lot of noncompleted multipart uploads and some files are missing without an exception generated.
I reviewed the smart_open code and see that there is no respond check in the close call.
However, documentation https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html.
that response always 200 and it is important that you check the response body to determine whether the request succeeded.

I think the response has to be checked and multipart upload has to be aborted in the case of the failure and also exception is thrown further.

#### Steps/code to reproduce the problem
this issue is difficult to reproduce as it appears randomly
We run code in AWS lambda with 1000 parallelism
The function reads line delimited JSON and JSON document to multiple output files
One time function can process file successfully another time it generates not completed multi parts uploads without letting code know that it is failing.
```python
def process_file_multiple_outputs(params):
    cnt = 0
    formatted_cnt = 0
    errors_cnt = 0
    formatter = params['formatter']
    compression = params['compression']
    file_id = params['src_file_id']
    src_file = params['src_file_name']
    dst_file = params['data_file_s3_path']
    error_file = params['error_file_s3_path']
    csv_format = True if params['csv_format'] == 'csv' or re.search(".*\.csv(\..*|$)", src_file) else False
    dst_files = dict()
    try:
        with (smart_open(src_file, "rb")) as src:
            for line in open_as_csv(csv_format, decompress_if_missing_extension(compression, src_file, src)):
                cnt += 1

                errors, data = formatter(file_id, line.decode("utf-8").strip() if not csv_format else line, cnt)
                formatted_cnt += len(data)
                errors_cnt += len(errors)

                for table_name in data:
                    if table_name not in dst_files:
                            dst_files[table_name] = smart_open(dst_file + '-' + table_name + '.json.gz', "wb")

                    write_json_data(dst_files[table_name], data[table_name])

                if len(errors) != 0:
                        if 'ERRORS' not in dst_files:
                            dst_files['ERRORS'] = smart_open(error_file + '-errors' + '.json.gz', "wb")
                        write_json_data(dst_files['ERRORS'], errors)

    except Exception as e:
        result = "Failure"
        error_msg = format_exc()
        error_msg += "\n Error at line %d  : %s" % (cnt, str(e))

    else:
        result = "Success"
        error_msg = None

    finally:
        for _, file in dst_files.items():
            file.close()

    return ({'src_file_id': file_id,
             'src_num_lines': cnt,
             'csv_num_lines': formatted_cnt,
             'csv_error_lines': errors_cnt,
             'csv_file_name': dst_file,
             'result': result,
             'error_msg': error_msg,
             'is_processed': True})
```

#### Versions

Please provide the output of:

Python 3.6.8 
smart-open==1.7.1
boto==2.49.0
boto3==1.9.8
botocore==1.12.8

**Comment by mpenkov** [comment]
Thank you for reporting this problem. Are you able to make a PR?

**Comment by vmaksimenko** [comment]
Hi Michael,

What details do you need?
I am wroking for Samsung Knox B2B analytics team as a big data system
architect Vancouver Canada.

Valery

**Comment by vmaksimenko** [comment]
Michael,

More I am researching this issue more I think it might be not smart open
problem but boto client itself. I see smart open uses multipart uploading
interface that boto client has. Those calls handle error error responds and
rise exeptions accordently. It is could be that aws api service calls
within our account scope got overloaded and doesnt return any respond event
an error one. I think I will contact aws support team for this issue.
Best regards
Valery

**Comment by mpenkov** [comment]
By "PR", I meant ["pull request" on github](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests): if there is a bug or deficiency on the smart_open side, are you able to fix it yourself and contribute to our project?

**Comment by vmaksimenko** [comment]
Hi Michael,

this was funny I think I was working to much these days. We  are looking to
resolve this issue in case we find a solution I will do it if it is a part
of the smart open.

Valery

**Comment by mpenkov** [comment]
@vmaksimenko Did you end up making any progress on the problem?

I did some digging, and found out that the multipart upload `complete()` function [_always_ returns the created S3 object in Python](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.MultipartUpload.complete). If there was any sort of error, it raises an exception, which will propagate to the user. So, checking the return value of the `complete` function is not necessary from `smart_open`'s point of view.

I think your code should catch and deal with the exception as necessary. For example, you can examine the `fout._parts` object for the constituent parts of the upload, and complete the upload yourself by doing `fout._mp.complete()`.

In any case, I'd be interested to hear about the cause behind these failed uploads. It should be obvious from the above-mentioned exceptions.

**Comment by vmaksimenko** [comment]
Hi Michael,
Thank you for the update, I was not able to solve it within a reasonable
time. We are using a workaround, save files in temporary space and then
transfer it file by file when processing is finished.
However it caused us another problem that in lambda temp space is limited
by 512MB and the smart_open buffering approach is preferred here.
I also learned that lambda has another limit only 10 service calls and
boto3 client complete multipart upload call some specific result checking.

Invocation frequency (requests per second)

10 x concurrent executions limit (synchronous
<https://docs.aws.amazon.com/lambda/latest/dg/invocation-sync.html> – all
sources)

10 x concurrent executions limit (asynchronous
<https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html> –
non-AWS sources)

Unlimited (asynchronous – AWS service sources
<https://docs.aws.amazon.com/lambda/latest/dg/lambda-services.html>)
*Processing of a Complete Multipart Upload request could take several
minutes to complete. After Amazon S3 begins processing the request, it
sends an HTTP response header that specifies a 200 OK response. While
processing is in progress, Amazon S3 periodically sends white space
characters to keep the connection from timing out. Because a request could
fail after the initial 200 OK response has been sent, it is important that
you check the response body to determine whether the request succeeded.*

In our case we wrote kind universal JSON flattener. Lambda reads one very
JSON file (mongodb collections documents)  and one source line could be
mapped up to 30 files and one file mapped to 100+ files. Filling data in
the output files is very random and based on what documents are in the
files and what order they are.

As I stated in the issue a problem that we are not capturing any exception
in this case. Our code was written that we try to process the file if there
is any exception happened we record it and try to reprocess this file
multiple times before fail then process it locally on etl server.
In this particular case we notice that from the same lambda execution I see
some files were created and some are missing and it is very random. If you
run processing the same file second time all files were generated.
Then I queried for the incompleted multipart uploads and found that those
files were incomplete.
I looked boto/bucket.py source code for complete_multipart_upload method.
https://github.com/boto/boto/blob/develop/boto/s3/bucket.py

And it is not obvious here how does code support document statement (.
After Amazon S3 begins processing the request, it sends an HTTP response
header that specifies a 200 OK response. While processing is in progress,
Amazon S3 periodically sends white space characters to keep the connection
from timing out. Because a request could fail after the initial 200 OK
response has been sent, it is important that you check the response body to
determine whether the request succeeded.)
I see the only one-time request in code and it always returns respond but
what if 200 OK received but you still have to wait till s3 complete your
request. Who is responsible to do it.

This is an example of what we run as lambda
row_map function returns a dictionary where the key is a file where
specific JSON keys are mapped to be output
you can see there is one try only and it has to catch exceptions coming
from smart_open but in our case, it doesn't

def process_file(params):

    file_id = params['src_file_id']
    src_file = params['src_file_name']

    data_file_s3_path = params['data_file_s3_path']
    dst_files = dict()

    try:

        with smart_open(src_file, "rb") as src:

            for line in src:

                data = row_map(line.decode("utf-8").strip())
                split_data = defaultdict(lambda: list())

                for d in data:
                    split_data[d['feature']].append(d)

                for feature in split_data:
                    if feature not in dst_files:
                        dst_files[feature] =
smart_open(data_file_s3_path.format(feature=feature.lower()) +
'.json.gz', "wb")

                    write_json_data(dst_files[feature], split_data[feature])
                    for doc in split_data[feature]:
                        line = json.dumps(doc).encode('utf-8')+b'\n'
                        dst_files[feature].write(line)

            for _, file in dst_files.items():
                file.close()

        result = "Success"
        error_msg = None

    except Exception as e:

        result = "Failure"
        error_msg = format_exc()
        error_msg += "\n Error : %s" % (str(e))

    return ({'src_file_id': file_id,
             'result': result,
             'error_msg': error_msg,
             'is_processed': True})

**Comment by mpenkov** [comment]
What is the output of your script? In particular, what exceptions do you end up encountering? Seeing some stack traces would be helpful.

Also, I think you need to do better exception handling. One thing I would do is:

```python
try:
   for url, fout in dst_files.items():
       try:
           fout.close()  # This is the part that completes the multipart upload
       except Exception:  # maybe pick a more specific exception once you know what 
           ... # Handle the exception here
```

For the specific handling, there are several ideas:

- Try closing the file again
- Try completing the multipart upload yourself
- Add sleep statements to throttle your requests if you think you're running into limits

Generally, if you suspect the problem happens when you're trying to complete the multipart upload, then the "hard work" of uploading the parts to S3 is already done. All you need to do is assemble the parts in the correct order.
