### ISSUE TITLE
Provide public API to get version id after writing to S3

### ISSUE THREAD

**Issue by acarapetis** [RaRe-Technologies/smart_open#392]
#### Problem description

I'm using smart_open to stream large file uploads to S3, for which it works beautifully; but I've run into a bit of an inconvenience: I'm using S3 versioning, and after uploading an object I'd like to know its version_id. This is currently possible, but (as far as I can tell) only by using undocumented internals:

```python
from smart_open import open
target = open('s3://my-versioned-bucket/some-object', 'wt')
with target as fh:
    fh.write('hello there!')
version_id = target._object.version_id
```

It'd be great if there was a documented public API for accessing (transport-specific) details of the file you just created.

**Comment by cdosborn** [comment]
https://github.com/RaRe-Technologies/smart_open/blob/develop/howto.md#how-to-access-s3-object-properties
```
>>> from smart_open import open
>>> with open('s3://commoncrawl/robots.txt') as fin:
...    print(fin.readline().rstrip())
...    boto3_s3_object = fin.to_boto3()
...    boto3_s3_object.version_id
```

**Comment by acarapetis** [comment]
@cdosborn Cool, glad to see this make it into 2.0.0! Sadly, I think the current implementation is subject to race conditions: [in to_boto3](https://github.com/RaRe-Technologies/smart_open/blob/cc247c59411bf693c33eae54d265b310dd78bd9f/smart_open/s3.py#L525), my guess is that the code
```python
     return s3.Object(self._object.bucket_name, self._object.key)
```
will always get the *latest* version of this object, not the same version as self._object. I'll verify whether this is the case, and if so, submit a PR to fix it.

**Comment by mpenkov** [comment]
@acarapetis Yes, you're right, that call should use the  `_get()` function:

https://github.com/RaRe-Technologies/smart_open/blob/cc247c59411bf693c33eae54d265b310dd78bd9f/smart_open/s3.py#L263

Can you make a PR?
