### ISSUE TITLE
Feature Request: Support `-` for stdin and stdout

### ISSUE THREAD

**Issue by reece** [RaRe-Technologies/smart_open#397]
#### Problem description

It is common in Unix environments to use `-` to mean stdin or stdout (depending on context). The hyphen convention is supported by the Python [fileinput](https://docs.python.org/3.7/library/fileinput.html) library. 

smart_open does not support this convention.

#### Steps/code to reproduce the problem

```
In [1]: import smart_open                                                                                                                                                   
In [2]: smart_open.open("-")                                                                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: '-'
```

#### Versions

```python
>>> import platform, sys, smart_open 
... print(platform.platform()) 
... print("Python", sys.version) 
... print("smart_open", smart_open.__version__)                                                                                                                             
Linux-5.3.0-23-generic-x86_64-with-Ubuntu-19.10-eoan
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]
smart_open 1.9.0
```

**Comment by piskvorky** [comment]
Smart_open mimics the built-in `open()`, which doesn't recognize `-` as a special filename. It will treat `-` as a file with the literal filename `-`, and so will smart_open.

In Python, you use Unix stdin/stdout via `sys.stdin` / `sys.stdout`, which are already opened streams.

**Comment by reece** [comment]
I understand the cause fully.

This was a feature request to support a common convention that is in keeping with the spirit of smart_open to abstract the many ways that people refer to files and streams.

Thanks for your reconsideration.

**Comment by mpenkov** [comment]
I think treating hyphen as stdout (or stdin, depending on the context) is a common convention, but only in command-line applications.

smart_open is a **library** (as opposed to a command-line application), so I think conforming to the above convention does not make sense in our case.
