### ISSUE TITLE
Feature request: Supply parameters to registered compression handlers

### ISSUE THREAD

**Issue by goodside** [RaRe-Technologies/smart_open#399]
Currently, when a compression handler is registered via `register_compressor('.ext', _handle_ext)`, the function `_handle_ext` is passed only two arguments, `file_obj` and `mode`. Many compressors support additional parameters that can greatly affect their behavior. For example, Zstandard supports setting compression levels (trading between speed and compression ratio), setting the number of threads to use during compression, or specifying the uncompressed file size in advance so it can be written into header metadata. Many users of `smart_open` who need to register their own compressors are also likely to need these parameters, as “exotic” compression is most useful in performance-critical scenarios.

Currently, these parameters must be defined in the user’s custom `_handle_ext()` function before it is registered, which is far from ideal as some options (like uncompressed file size) are highly specific to the data being written. Data-specific options can only really be set by “juggling” multiple variations of `_handle_ext()`, registering custom versions and re-registering a default version after each operation.

I propose `open()` should support a `compression_params={}` dictionary argument, which would then be passed to the registered handler, analogous to the existing `transport_params={}`. I’d also suggest this argument be added to `register_compressor()`, so parameters may both be set globally for convenience and be extended for individual calls to `open()`.

I would be interested in writing a PR for this feature if maintainers agree it is valuable and likely to be merged. It should be straightforward to implement.

**Comment by mpenkov** [comment]
Isn't it simpler to do something like this instead?

```python
import smart_open
import zstandard as zstd

with smart_open.open(..., 'rb') as fh:
    cctx = zstd.ZstdCompressor(...)  # include as many options here as necessary
    reader = cctx.stream_reader(fh)
    while True:
        chunk = reader.read(16384)
        if not chunk:
            break

        # Do something with compressed chunk.
```

**Comment by goodside** [comment]
I was trying to make it possible to `open()` zstd files as effortlessly as gzip/bz2, so as to have code that accepts arbitrary path strings and doesn’t need to check the extension to decide how to read/write. But I see the logic that if you need do anything that requires parameters you should just do compression yourself explicitly and write the binary stream. Feel free to close if nobody else thinks this is useful.
