### ISSUE TITLE
Behavior of file:// URLs with two slashes

### ISSUE THREAD

**Issue by kenahoo** [RaRe-Technologies/smart_open#407]
#### Problem description

I'm trying to intercept `file:` URL-based paths so that I can auto-create the given directory (or die saying it doesn't exist) at the beginning of my program, rather than dying an hour later when the results are written using `smart_open.open(url, 'w')`.

If the user specifies a URL like `file://foo/bar`, there seems to be an inconsistency between how `urllib` and `smart_open` interpret the path - the former as `/bar` on a server `foo`, the latter as a relative path `foo/bar`:

```
>>> from urllib.parse import urlparse
>>> urlparse('file://foo/bar')
ParseResult(scheme='file', netloc='foo', path='/bar', params='', query='', fragment='')

>>> from smart_open import open as smart_open
>>> with smart_open('file://foo/bar', 'w') as fh:
...   fh.write("hi\n")
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 308, in open
    errors=errors,
  File "venv/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 517, in _shortcut_open
    return _builtin_open(parsed_uri.uri_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'foo/bar'
```

I know that [two-slash `file:` urls are technically invalid](https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files), but both `urlparse` and `smart_open` seem to allow them, unfortunately using different semantics.

#### Proposal

What would be great is if `smart_open` would expose its mechanism for translating a URL into a local path (returning `None` if it's not a local path), so that I could avoid using `urllib.urlparse` and `urllib.unquote` to fudge it in a way that's probably different somehow from what `smart_open` is doing internally.  

```python
local_path = smart_open.as_local_path(path)
if local_path is not None:
  os.makedirs(local_path, exist_ok=True)
with smart_open(path + '/file.txt', 'w') as fh:
  fh.write("hi mom\n")
```

Or even better, provide some cross-input way to "make a directory" so that files can later be written into that directory, like so:

```python
smart_open.makedirs(path, exist_ok=True)
with smart_open(path + '/file.txt', 'w') as fh:
  fh.write("hi mom\n")
```

That has the benefit of doing the right thing even if the location is on a remote server.

#### Workaround

Right now I'm doing this:

```python
import re
from urllib.parse import urlparse, unquote

def url_to_local_path(url):
    parsed = urlparse(url)
    if parsed.netloc is not None and parsed.netloc != 'localhost':
        # https://en.wikipedia.org/wiki/File_URI_scheme
        raise ValueError(f"Invalid URL '{url}', did you mean '{parsed.scheme + ':///' + parsed.netloc + parsed.path}'?")
    return unquote(parsed.path)

if not re.match(r"^\w+:", path):
    # This is a local file, make sure the directory we're writing to exists
    os.makedirs(path, exist_ok=True)
elif re.match("^file:", path):
    # Also a local file
    os.makedirs(self.url_to_local_path(path), exist_ok=True)
```

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```

```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
smart_open 1.9.0
```

**Comment by mpenkov** [comment]
Thank you for raising this, but handling the edge cases of invalid URLs is out of scope for us, so I'm closing the issue.
