### ISSUE TITLE
GCS Writing multiple times does not work

### ISSUE THREAD

**Issue by mirkogrcic** [RaRe-Technologies/smart_open#417]
#### Problem description
When I open a GCS bucket object and write multiple times only the data of the first write is stored in the object
The logs must show that it uploaded multiple parts (2+) like this `INFO:smart_open.gcs:uploading part #2`

Be sure your description clearly answers the following questions:

- What are you trying to achieve?
Upload a 1 MB file to a google bucket object

- What is the expected result?
I expect the file to be fully uploaded to the GCS

- What are you seeing instead?
Only the first part was uploaded, usually part size is about 200 to 300 KB

#### Steps/code to reproduce the problem

```Python3
import os
import io
import logging
from smart_open import open

logging.basicConfig(level=logging.INFO)

url = "gs://smart-open-784235/test-object"
size = 99 * 1024

data = io.BytesIO()
with open(url, "wb") as f:
    for _ in range(10):
        buffer = os.urandom(size)
        data.write(buffer)
        f.write(buffer)

data = bytes(data.getbuffer())
with open(url, "rb") as f:
    remote_data = f.read()

print("Local size:", len(data))
print("Remote size:", len(remote_data))
```
Output:
```
INFO:smart_open.gcs:uploading part #1, 304128 bytes (total 0.000GB)
INFO:smart_open.gcs:uploading part #2, 304128 bytes (total 0.001GB)
INFO:smart_open.gcs:uploading part #3, 304128 bytes (total 0.001GB)
INFO:smart_open.gcs:uploading part #4, 101376 bytes (total 0.001GB)
INFO:google.resumable_media.requests.download:No MD5 checksum was returned from the service while downloading https://storage.googleapis.com/download/storage/v1/b/smart-open-784235/o/test-object?generation=1581104519907572&alt=media
(which happens for composite objects), so client-side content integrity
checking is not being performed.
Local size: 1013760
Remote size: 304128
```

#### Versions

Linux-5.4.13-201.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Python 3.7.6 (default, Dec 19 2019, 22:52:49) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
smart_open 1.9.0

I have downloaded smart-open from github yesterday and used it instead of the repo version as there is not GCS support in the repos
The latest commit at the time of download was https://github.com/RaRe-Technologies/smart_open/commit/72818ca6d3a0a99e1717ab31db72bf109ac5ce65

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by petedannemann** [comment]
Thanks for reporting this. It looks like I made some mistakes with the multipart uploading that I'll try to fix this week.

**Comment by mirkogrcic** [comment]
Thank you very much, very much appreciated.
