### ISSUE TITLE
gs URI scheme not supported

### ISSUE THREAD

**Issue by yongyct** [RaRe-Technologies/smart_open#423]
#### Problem description
- What are you trying to achieve?
Trying to use this with GCS objects for streaming the latter
- What is the expected result?
GCS object to be opened normally as per README
- What are you seeing instead?
Got: `NotImplementedError: unknown URI scheme 'gs' in 'gs://...`

##### My Code
```python
import smart_open
smart_open.open('gs://...')
```
##### My Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\path\to\anaconda3\envs\test\lib\site-packages\smart_open\smart_open_lib.py", line 308, in open
    errors=errors,
  File "C:\path\to\anaconda3\envs\test\lib\site-packages\smart_open\smart_open_lib.py", line 490, in _shortcut_open
    parsed_uri = _parse_uri(uri)
  File "C:\path\to\anaconda3\envs\test\lib\site-packages\smart_open\smart_open_lib.py", line 737, in _parse_uri
    "unknown URI scheme %r in %r" % (parsed_uri.scheme, uri_as_string)
NotImplementedError: unknown URI scheme 'gs' in 'gs://...'
```

#### Versions
1.9.0

**Comment by piskvorky** [comment]
CC @petedannemann is this expected?

**Comment by petedannemann** [comment]
@yongyct GCS has not yet been officially released and is not yet on Pypi. If you want to use GCS functionality please pip install from github:
```bash
pip install git+https://github.com/RaRe-Technologies/smart_open
```

**Comment by PrzemekPobrotyn** [comment]
@petedannemann hi, when can we expect a new pypi release?

**Comment by piskvorky** [comment]
CC @mpenkov .

**Comment by petedannemann** [comment]
@mpenkov can we close this?

**Comment by mpenkov** [comment]
Yes, I think closing this is appropriate.
