### ISSUE TITLE
Add a generic way to call smart_open API to allow change of storage without changing code

### ISSUE THREAD

**Issue by gfournier** [RaRe-Technologies/smart_open#425]
#### Problem description

New feature / new way to call the smart_open API.
We can contribute the development if idea accepted.

- What are you trying to achieve?
Write a generic code and just change one variable to switch between S3 storage / FileStorage ...

- What is the expected result?
Example:
```python
from smart-open import backends
backend = backends.s3(...put some config here)
with backend.open('path') as f:
    ... do stuff
```

So changing the backend at the beginning of the code would change the behaviour everywhere without changing the paths in the open

- What are you seeing instead?
Currently if I want to change the way the files are stored / read I need to change manually the paths in my code.

**Comment by mpenkov** [comment]
Interesting idea. You're putting the config inside the context manager as opposed to the `open` call.

When would someone use something like this? Can you think of a real-life use-case?

There is already this possibility:

```
cfg = {'s3://...': dict(foo=bar, ...), 'file:///....': dict(...), }
uri = 's3://...'
with open(uri, **cfg.get(uri, {}) as f:
    ...
```

which seems to achieve approximately the same thing, a little less elegantly, but with no changes to the codebase.

**Comment by gfournier** [comment]
Yes we thought about that idea.
But we want to write:
```
uri = '/path/to/my/resource'
with open(uri) as f:
  ...
```

So that the code is not bound with the backend itself (not part of the URI) and change (by config) the context of the open operation.

If it's with S3 it will add the connection parameters and the `s3://bucket` prefix, if it's a file it will add the `file://` prefix, etc...

Some real-life use case (for us):
* change the backend for unit tests (from file to in-memory for example)
* change the backend for writing apps (from file when deploying locally or on a VM to S3 to deploy on containers for example)

**Comment by mpenkov** [comment]
Sounds like something that's a bit too narrow in scope for our library.

In theory, you could implement the backends thing entirely outside of smart_open, right?

**Comment by gfournier** [comment]
Ok understood, we can implement it outside of smart_open.
We let you know when we release this adapter on top. of smart_open.

**Comment by mpenkov** [comment]
Yes, please do. I'd like to take a look at it when it's ready.
