### ISSUE TITLE
Migrate to boto3

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/smart_open#43]
Check if boto3 is production-ready and [migrate all code from boto to boto3](http://boto3.readthedocs.org/en/latest/guide/migration.html).

**Comment by anupamme** [comment]
I tried running smart_open on ubunty (15.10) and when I run python3.5 setup.py test I get following error message

pkg_resources.DistributionNotFound: The 'httpretty>=0.8.8' distribution was not found and is required by the application

And I am not able to install httpretty 0.8.8 or higher version on this machine (I can get 0.8.6 version running by directly downloading the deb package). I opened a ticket (https://github.com/gabrielfalcao/HTTPretty/issues/269)

So I am not sure how to go about fixing this. Any help will be appreciated.

output of uname -a:

Linux instance-8 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linu

**Comment by asieira** [comment]
I would suggest that event if boto3 is supported, existing implementation using boto 2 is kept as well.

There are many things boto3 hasn't implemented yet. To give one example, the lack of [explicit proxy support](https://github.com/boto/boto3/issues/338) would prevent me from continuing to use smart_open if it went boto3-only. See #35 for supporting evidence. :)

**Comment by piskvorky** [comment]
Thanks @asieira , that's the kind of practical feedback we need!

I don't have experience with boto3, and certainly wouldn't want to inconvenience users by a hasty switch.

**Comment by brunoalano** [comment]
+1

**Comment by vinayan3** [comment]
+1. I'm having issues with Python 3.5 and Boto 2.39. From what I've read Python 3x is better with boto3

**Comment by tmylk** [comment]
@vinayan3 What kind of issues are you having? Would be great to check they are resolved in boto3.

**Comment by tmylk** [comment]
Update on Boto3 : Proxy support still not implemented in https://github.com/boto/boto3/issues/338

**Comment by tmylk** [comment]
Our test dependeny moto has moved to boto3 unfortunately in ver 1.0.0

> * The normal @mock_<service> decorators will no longer work with boto. It is suggested that you upgrade to boto3 or use the standalone-server mode. If you would still like to use boto, you must use the @mock_<service>_deprecated decorators which will be removed in a future release.

**Comment by combinatorist** [comment]
+1

- I came in at boto3. 
- Currently, I use this library by string interpolating keys into paths
  - e.g. `smart_open('s3://mybucket/' + key)`
- but I really wish I could use boto3 objects (particularly for the advertised `smart_open.s3_iter_bucket` function)

**Comment by tim-schier-frontier** [comment]
I'm using moto and would like to move to moto>=1, but smart_open is holding me back due to boto3 vs boto support.
Even using @mock_s3_deprecated for my other moto usage is causing issues now with moto 1.0.1. It looks like a moto bug, but only a bug in the deprecated support for boto.

So yeah, boto3 momentum is building. Oh and it looks like proxy support has been added to boto3 now (ticket @tmylk linked to is closed as implemented).

**Comment by piskvorky** [comment]
@tim-schier-frontier can you help with the migration, open a PR?

**Comment by tim-schier-frontier** [comment]
@piskvorky great follow up - put money where my mouth is :) 
I am best placed to help with testing/trialing PRs, and also probably chipping in for funding the move (from my employer).
Love the product, hope to help out.

**Comment by mpenkov** [comment]
I think boto3 now supports proxies: https://github.com/boto/boto3/issues/338

The S3 component is already boto3-based. The tests are still boto-based, however. @menshikh-iv What should we do about this?

**Comment by menshikh-iv** [comment]
@mpenkov probably migrate tests to boto3 & close this issue

**Comment by mpenkov** [comment]
We should also upgrade moto to the most recent version.

**Comment by inksink** [comment]
I have read the [PR 164](https://github.com/RaRe-Technologies/smart_open/pull/164) which will migrate tests to boto3.
But there are many codes used boto in [smart_open_lib.py](https://github.com/RaRe-Technologies/smart_open/blob/master/smart_open/smart_open_lib.py). Do we have such a plan to migrate `smart_open_lib` to boto3?
I wish to reduce unnecessary external dependencies in my project.

**Comment by menshikh-iv** [comment]
@inksink yes, we want to migrate all to `boto3`
CC: @mpenkov

**Comment by carolingfish** [comment]
I noticed that commit on this has been merged. Any estimate on when the new package including the commit will be released?

**Comment by menshikh-iv** [comment]
@carolingfish I think I'll release it in the current month

**Comment by bkapoorUF** [comment]
Any update on when this will be released?

**Comment by menshikh-iv** [comment]
@bkapoorUF already released as `smart_open==1.6.0`
