### ISSUE TITLE
pip install smart_open[aws] gives smart-open 1.10.0 does not provide the extra 'aws'

### ISSUE THREAD

**Issue by jethrogillgren** [RaRe-Technologies/smart_open#465]
#### Problem description
Hi all, I can't install the AWS extras. Thanks for any assistance.
The README says to run:

```bash
$ pip install smart_open[aws]  
Collecting smart_open[aws]
  Downloading smart_open-1.10.0.tar.gz (99 kB)
     |████████████████████████████████| 99 kB 7.1 MB/s
  WARNING: smart-open 1.10.0 does not provide the extra 'aws'
```

But I get the above error.

#### Steps/code to reproduce the problem. 
`pip install smart_open[aws]`  

#### Versions
Tested on Ubuntu 18 LTS
``` python
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, sys, smart_open
>>> print(platform.platform())
Linux-4.15.0-1063-aws-x86_64-with-Ubuntu-18.04-bionic
>>> print("Python", sys.version)
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0]
>>> print("smart_open", smart_open.__version__)
smart_open 1.10.0
```

And Mac 10.15.4
```python
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, sys, smart_open
>>> print(platform.platform())
Darwin-19.4.0-x86_64-i386-64bit
>>> print("Python", sys.version)
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)]
>>> print("smart_open", smart_open.__version__)
smart_open 1.9.0
```

```bash
$ pip --version
pip 20.0.2 
```

The same occurs for `pip install smart_open[aws]==1.9.0` etc...

Many Thanks

**Comment by mpenkov** [comment]
The new extras feature are for the development version only. They haven't been released yet.

**Comment by petedannemann** [comment]
@mpenkov it seems like smart-open commonly get questions about unreleased features. Would it make sense to have a develop branch?

**Comment by mpenkov** [comment]
Yeah, I was just thinking the same thing.

**Comment by jethrogillgren** [comment]
Thanks guys.
Have found the [README](https://github.com/RaRe-Technologies/smart_open/blob/1.10.0/README.rst) on the latest tagged version, will continue with that.
Awesome project, it's working a treat so far!
