### ISSUE TITLE
Create a separate branch for development

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#466]
@mpenkov it seems like smart-open commonly get questions about unreleased features. Would it make sense to have a develop branch?

_Originally posted by @petedannemann in https://github.com/RaRe-Technologies/smart_open/issues/465#issuecomment-610366120_

**Comment by piskvorky** [comment]
Not critical. Now there's a bit of an earthquake, on account of the "optional extensions" refactoring.

But this is an exception – I expect README to be fairly stable.

**Comment by mpenkov** [comment]
Every time we roll out a new feature, it gets reflected on master. This includes changes to the README and the help file. So things like new backends, etc. will appear there and potentially confuse users.

As an aside, I'm surprised by how fast #465 was created. It was hours after the merge of the related PR.

**Comment by Amertz08** [comment]
There is the "Unreleased" section of the changelog. I probably should have put the change in there for my PR.

**Comment by mpenkov** [comment]
The current practice is for us to update the changelog as part of the release process, so we don't ask PR authors to do that. The reason is that if many PRs are open simultaneously, editing the changelog introduces merge conflicts that are a PITA to deal with.

**Comment by mpenkov** [comment]
We now have a develop branch.
