### ISSUE TITLE
Output using `csv` module is inconsistent with traditional `open` behaviour

### ISSUE THREAD

**Issue by burkovae** [RaRe-Technologies/smart_open#477]
#### Problem description

I'm using python 3.7 and `smart_open==1.11.1` under Windows 10. There is [this issue with python, csv, and Windows](https://stackoverflow.com/questions/3191528/csv-in-python-adding-an-extra-carriage-return-on-windows) which your would normally solve by the mentioned solution.

However, if I replace `open` with `smart_open.open` there seems to be a different behaviour. `smart_open` still adds new lines to the csv, as described in the following test.
 
#### Steps/code to reproduce the problem

```
platform win32 -- Python 3.7.5, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- 
...
cachedir: .pytest_cache
...
plugins: cov-2.8.1, mypy-0.6.0
collecting ... collected 1 item

tests/test_io.py::test_compatibility_with_csv_under_windows FAILED       [100%]
tests\test_io.py:53 (test_compatibility_with_csv_under_windows)
c1,c2

a1,b1

a2,b2

 != c1,c2
a1,b1
a2,b2


def test_compatibility_with_csv_under_windows():
        rows = [{'c1': 'a1', 'c2': 'b1'}, {'c1': 'a2', 'c2': 'b2'}]
    
        expected = 'c1,c2\na1,b1\na2,b2\n'
    
        with open('tests/test.csv', 'w+', newline='\n') as f:
            out = csv.DictWriter(f, fieldnames=['c1', 'c2'])
            out.writeheader()
            out.writerows(rows)
    
        with smart_open.open('tests/test_smart_open.csv', 'w+', newline='\n') as f:
            out = csv.DictWriter(f, fieldnames=['c1', 'c2'])
            out.writeheader()
            out.writerows(rows)
    
    
        with open('tests/test.csv', 'r') as f:
            content = f.read()
            assert content == expected
    
        with open('tests/test_smart_open.csv', 'r') as f:
            content = f.read()
>           assert content == expected
E           AssertionError: assert 'c1,c2\n\na1,b1\n\na2,b2\n\n' == 'c1,c2\na1,b1\na2,b2\n'
```

#### Versions

Please provide the output of:

```python
Windows-10-10.0.17134-SP0
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
smart_open 1.11.1
```

#### Checklist

Before you create the issue, please make sure you have:

- [ ] Described the problem clearly (hope so ❤️ )
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by burkovae** [comment]
The addational `\n` are the problem here.

```
assert 'c1,c2\n\na1,b1\n\na2,b2\n\n' == 'c1,c2\na1,b1\na2,b2\n'`
             ⬆️      ⬆️       ⬆️
```

**Comment by mpenkov** [comment]
Thank you for reporting this issue and providing sample code. I tried reproducing your issue on MacOS and Linux, but with no success. The assertion passes.

Unfortunately, I don't have access to a Win machine, so I cannot reproduce your issue. Are you able to diagnose it yourself and make a PR?

**Comment by burkovae** [comment]
Yes, i think i found it, see #478.
