### ISSUE TITLE
Release version 1.10.1

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#481]
This is a bugfix release that removes GCS support from 1.10.0 in order to work around [this gensim issue](https://github.com/RaRe-Technologies/gensim/issues/2779).

Originally, we planned to include a fix for the [logging issue](https://github.com/RaRe-Technologies/gensim/pull/2797) as well, but it turns out that smart_open version 1.10.0 does not suffer from that issue.

@menshikh-iv @piskvorky Please [compare the changes](https://github.com/RaRe-Technologies/smart_open/compare/1.10.0...release-1.10.1?expand=1) in this branch to the base tag (1.10.1) and let me know if this is good to release.

**Comment by piskvorky** [comment]
Looks alright. Nothing else worth backporting to 1.10 from the main branch?

**Comment by mpenkov** [comment]
OK, I've pushed 1.10.1 to PyPI: https://pypi.org/project/smart-open/1.10.1/

**Comment by piskvorky** [comment]
Great! I'll update the `develop` README as well.
