### ISSUE TITLE
Redundant GetObject requests when fetching file contents from S3

### ISSUE THREAD

**Issue by jcushman** [RaRe-Technologies/smart_open#494]
#### Problem description

When fetching the contents of a file from S3, smart_open sends two GetObject API requests -- one to fetch the file length, and one to fetch the contents. From an EC2 instance in the same region as the bucket, this doubles the cost of fetching the file.

The double request happens because there is one call to `_get` in `Reader.__init__`, solely to fetch the content length, and a second call to `_get` in `_SeekableRawReader._load_body`.

#### Steps/code to reproduce the problem

Here is a demo of the problem, enabling logging in botocore to see the requests sent:

```
In [1]: from smart_open import open
In [2]: import boto3
In [3]: import logging
   ...: boto3.set_stream_logger('botocore.endpoint', logging.DEBUG)
In [4]: with open('s3://my-bucket/my-object') as f:
   ...:     contents = f.read()
   ...:
2020-05-05 15:50:34,840 botocore.endpoint [DEBUG] Making request for OperationModel(name=GetObject) with params: ...{'url_path': '/my-bucket/my-object' 
...
2020-05-05 15:50:35,020 botocore.endpoint [DEBUG] Making request for OperationModel(name=GetObject) with params: {'url_path': '/my-bucket/my-object'
...
```

Performing the same load directly with boto3 triggers only a single API request:

```
In [6]: contents = boto3.resource('s3').Object('my-bucket', 'my-object').get()['Body'].read()
2020-05-05 15:54:28,232 botocore.endpoint [DEBUG] Making request for OperationModel(name=GetObject) with params: {'url_path': ...
```

#### Versions

```
Linux-4.14.173-137.229.amzn2.x86_64-x86_64-with-glibc2.2.5
Python 3.7.6 (default, Feb 26 2020, 20:54:15)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]
smart_open 2.0.0
```

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by piskvorky** [comment]
I remember we already hit this one. Maybe a regression?

@jcushman are you able to check why the second (superfluous) call to content length is there? Is it vital?

**Comment by jcushman** [comment]
As far as I can see this has been an issue since [this revision in 2017](https://github.com/RaRe-Technologies/smart_open/blob/fbc82cc04bf92e8c588c49c43ff5aff8234ea87d/smart_open/s3.py), though I may have missed a point where it was fixed and then regressed.

I think a light refactor could fix this. Content length can be extracted from the `_get` call in `_SeekableRawReader._load_body` via the `ContentRange` response header, so the question is just whether it is mandatory to have content length before that response comes back.

Content length is used before that response in these situations:

* In `_SeekableRawReader._load_body` before the `_get` call, to detect reads of empty files or ones that are already seeked to the end of the file. These could be handled after the `_get` instead.
* In `_SeekableRawReader.read` to detect reads past the end of the file. This check could be moved a line lower.
* In `Reader.read`: this could go a line lower.
* In `Reader.seek`: this should probably call `_SeekableRawReader._load_body`

So I think it would just take some messing around to make sure _content_length is always populated by the time it's needed.

Regarding regressions, it might be handy to have a pytest fixture that can assert how many API requests are made. Something like:

```
@pytest.fixture
def boto_calls(monkeypatch):
    boto_calls = defaultdict(int)
    real_make_request = Endpoint.make_request
    def mock_make_request(self, operation_model, *args, **kwargs):
        boto_calls[operation_model.name] += 1
        return real_make_request(self, operation_model, *args, **kwargs)
    monkeypatch.setattr(Endpoint, "make_request", mock_make_request)
    yield boto_calls

def test_foo(boto_calls):
    # do stuff ...
    assert boto_calls == {'GetObject': 1}
```

**Comment by piskvorky** [comment]
Sounds good to me. *Implicit* file size is not part of any `open` or `smart_open` contract I'm aware of. CC @mpenkov WDYT?

And wherever the size is needed *explicitly*, we should be able to either get it out of the conjoining `_load_body` call, or have the user explicitly fetch it themselves (if they need it).

@jcushman would you be able to write a PR for this?
