### ISSUE TITLE
export transport.register_transport?

### ISSUE THREAD

**Issue by wanwe** [RaRe-Technologies/smart_open#500]
#### Problem description

is it possible to expose "transport.register_transport"? 
I want to slightly different version of s3 protocol, add another private s3 schema.
I could not register it like what it's documented [here](https://github.com/RaRe-Technologies/smart_open/blob/develop/extending.md), due to "register_transport" is not exported

Thank you !

**Comment by mpenkov** [comment]
What do you mean by "not exported"?

```
$ python
Python 3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import smart_open.transport
>>> smart_open.transport.register_transport
<function register_transport at 0x10bf60680>
```

**Comment by wanwe** [comment]
thanks for the reply !
It turns out something went bad with my package installation, I was getting error "ModuleNotFoundError: No module named 'smart_open.transport'". 

after uninstall and force-reinstall, it works now

closing this...Thanks again !
