### ISSUE TITLE
Rename ASB to something more suitable

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#501]
That's fine. Let's call it `azure` then, or `azureblob` / `AzureBlob`. Nobody knows what ASB is.

_Originally posted by @piskvorky in https://github.com/RaRe-Technologies/smart_open/pull/444/files_

**Comment by piskvorky** [comment]
@petedannemann is on it. I saw him fix this in #498 (424fdcf1b54d197641d713f6b47bb34368d284b1 and others).
