### ISSUE TITLE
gzip can not chose  compresslevel in compression.py

### ISSUE THREAD

**Issue by SchopenhauerZhang** [RaRe-Technologies/smart_open#503]
https://docs.python.org/3/library/gzip.html
like this:
def _handle_gzip(file_obj, mode,compresslevel:int=9):
    import gzip
    return gzip.GzipFile(fileobj=file_obj, mode=mode, compresslevel=compresslevel)

**Comment by danielloader** [comment]
You can just re-register the compressor in a pinch:
```
from smart_open import open, register_compressor

def _handle_gzip(file_obj, mode):
    import gzip
    return gzip.GzipFile(fileobj=file_obj, mode=mode, compresslevel=3)


register_compressor('.gz', _handle_gzip)
```
