### ISSUE TITLE
Handle missing .name attribute more robustly

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/smart_open#512]
Currently, it's a TODO, far from ideal.

https://github.com/RaRe-Technologies/smart_open/blob/0a3619144a75ea002304c487b8f8a9ee2c867c33/smart_open/smart_open_lib.py#L403

**Comment by petedannemann** [comment]
What were you thinking for this @mpenkov? Raise an error if it is missing and fix any that don't currently have it?

**Comment by mpenkov** [comment]
I think we can just do `fobj.name = uri` because at this stage we are sure that `uri` is a string.

**Comment by mpenkov** [comment]
Already done.
