### ISSUE TITLE
In setup.py, replace piskvorky with RaRe-Technologies

### ISSUE THREAD

**Issue by impredicative** [RaRe-Technologies/smart_open#526]
In the `develop` branch, `setup.py` has the line:

> url='https://github.com/piskvorky/smart_open',

It should instead have:

> url='https://github.com/RaRe-Technologies/smart_open',

**Comment by piskvorky** [comment]
The redirect works, but why not.

How did you find this, what's your motivation?

**Comment by impredicative** [comment]
> How did you find this, what's your motivation?

I found this while reading `setup.py` for the package's requirements. I'm currently having a random error with `urllib3` while using `smart_open`; I'm investigating.

Despite the redirect, the motivation is accuracy.

**Comment by mpenkov** [comment]
Not worth bothering with this IMHO.

**Comment by impredicative** [comment]
> Not worth bothering with this IMHO.

That's irresponsible and unprofessional. I guess the peak days of this package are behind it.

**Comment by impredicative** [comment]
It's time to stop recommending the use of this unprofessional package.

**Comment by impredicative** [comment]
I'm going to go ahead and delete all my upvoted StackOverflow answers that mentioned the use of this package.
