### ISSUE TITLE
smart_open.open does not handle open(file_descriptor) by passing it off to os.open, exception raised

### ISSUE THREAD

**Issue by davidparks21** [RaRe-Technologies/smart_open#528]
#### Problem description

The Python documentation states that the built-in `open` function accepts a integer file descriptor.

https://docs.python.org/3/library/functions.html#open

I have globally replaced `open` with `smart_open.open` but some library code is calling `open(file_descriptor)`.
I expected `smart_open.open` to hand off to `open` when the parameter is an integer.

Specifically quoting from smart_open's README.md:

> smart_open is a drop-in replacement for Python's built-in open(): it can do anything open can (100% compatible, falls back to native open wherever possible), plus lots of nifty extra stuff on top.

The exception occurs at `smart_open_lib.py:397` where smart_open only accepts a string or file-like object, but has no apparent provision for an integer file-descriptor.

#### Steps/code to reproduce the problem
This minimally reproducible example was taken directly from the library function that failed, specifically that's a utility function used by PyCharm: https://github.com/python/cpython/blob/master/Lib/multiprocessing/util.py:420-422
```
import smart_open
import os
import sys


# Default python works
fd = os.open(os.devnull, os.O_RDONLY)
f = open(fd, closefd=False)

# With smart open an exception is raised, should had off to system default open function
fd = os.open(os.devnull, os.O_RDONLY)
f = smart_open.open(fd, closefd=False)
```

```
Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/project_neural_mouse/src/ARCHIVE/scratch/scratch_58.py", line 12, in <module>
    f = smart_open.open(fd, closefd=False)
  File "/usr/local/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 225, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/usr/local/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 397, in _open_binary_stream
    raise TypeError("don't know how to handle uri %r" % uri)
TypeError: don't know how to handle uri 6
```

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```

```
Linux-4.15.0-108-generic-x86_64-with-glibc2.27
Python 3.8.2 (default, Apr 15 2020, 17:10:03) 
[GCC 7.5.0]
smart_open 2.1.0
```
#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [X] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

**Comment by piskvorky** [comment]
You're right, the Python 3 docs do allow for integer value of `file`. I don't remember that from Python 2, this must be some novelty we missed during the migration.

We definitely want to support anything the built-in supports, so I marked this as a bug. Thanks for reporting.

Are you able to open a PR with a fix?

**Comment by davidparks21** [comment]
I will try to do a fix for it and send a PR, it should be easy to correct, but I can't do it at this moment so I won't promise I'll find the time. But if I do have some time free in the next few days I'll reply here.
