### ISSUE TITLE
s3_iter_bucket: stream instead of downloading full content?

### ISSUE THREAD

**Issue by spinlud** [RaRe-Technologies/smart_open#529]
Is it somehow possible to use `s3_iter_bucket` to open a stream for each key instead of downloading the full content? The actual behaviour could be problematic for very large files that do not fit in memory.

**Comment by piskvorky** [comment]
It is possible, but defeats the purpose of `s3_iter_bucket()`.

If you need just the keys, and are OK with downloading the data yourself later, why not simply list the keys (strings) and open them with `smart_open` as/when needed?

There's no point complicating the situation with parallel `s3_iter_bucket()` downloads, when you're not actually downloading anything.

**Comment by spinlud** [comment]
Well, it would be nice to have an option inside s3_iter_bucket (or maybe a new method) to switch from downloading to streaming mode per key (I am using smart_open for its streaming functionalities).

Actually I have to list the keys using `boto3.client('s3').list_objects_v2(...)` and then iterate over the keys with `smart_open.open(...)`, while it seems reasonable to have all this wrapped inside `smart_open`,  just my thought.

**Comment by piskvorky** [comment]
Yes, listing keys and then opening the ones you need seems the way to go. But I'll leave this open for @mpenkov 's thoughts.

**Comment by mpenkov** [comment]
IMO smart_open should focus on streaming. Listing a bucket (which is essentially what this feature request boils down to) is already covered by boto3 reasonably well, and offering a new abstraction over that isn't going to bring much value.

**Comment by piskvorky** [comment]
Agreed. Sorry @spinlud – that's for the suggestion, but closing as "won't fix".
