### ISSUE TITLE
Smartopen failing on Windows

### ISSUE THREAD

**Issue by zjafriec** [RaRe-Technologies/smart_open#531]
We called smart_open.open() on a s3 link on a Windows machine and got the following error inside the smartopen library:

...
    with open(input_file, 'rb') as fin:
C:\ProgramData\Anaconda3\lib\site-packages\smart_open\smart_open_lib.py:225: in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
C:\ProgramData\Anaconda3\lib\site-packages\smart_open\smart_open_lib.py:401: in _open_binary_stream
    fobj = submodule.open_uri(uri, mode, transport_params)
C:\ProgramData\Anaconda3\lib\site-packages\smart_open\s3.py:162: in open_uri
    parsed_uri = parse_uri(uri)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

uri_as_string = 's3://secret:secret@input-location\\dummy_file.txt'

    def parse_uri(uri_as_string):
        #
        # Restrictions on bucket names and labels:
        #
        # - Bucket names must be at least 3 and no more than 63 characters long.
        # - Bucket names must be a series of one or more labels.
        # - Adjacent labels are separated by a single period (.).
        # - Bucket names can contain lowercase letters, numbers, and hyphens.
        # - Each label must start and end with a lowercase letter or a number.
        #
        # We use the above as a guide only, and do not perform any validation.  We
        # let boto3 take care of that for us.
        #
        split_uri = smart_open.utils.safe_urlsplit(uri_as_string)
        assert split_uri.scheme in SCHEMES

        port = DEFAULT_PORT
        host = boto.config.get('s3', 'host', DEFAULT_HOST)
        ordinary_calling_format = False
        #
        # These defaults tell boto3 to look for credentials elsewhere
        #
        access_id, access_secret = None, None

        #
        # Common URI template [secret:key@][host[:port]@]bucket/object
        #
        # The urlparse function doesn't handle the above schema, so we have to do
        # it ourselves.
        #
        uri = split_uri.netloc + split_uri.path

        if '@' in uri and ':' in uri.split('@')[0]:
            auth, uri = uri.split('@', 1)
            access_id, access_secret = auth.split(':')

>       head, key_id = uri.split('/', 1)
E       ValueError: not enough values to unpack (expected 2, got 1)

It looks like there's an issue on windows machines with the usage of uri.split() in the smart_open library.

**Comment by mpenkov** [comment]
> uri_as_string = 's3://secret:secret@input-location\dummy_file.txt'

I think the issue is you're using a backslash (\) as the separator between the bucket and key. You should use a slash (/).
