### ISSUE TITLE
Installing without AWS dependencies?

### ISSUE THREAD

**Issue by justindujardin** [RaRe-Technologies/smart_open#533]
First, thanks for building the awesome library. It works great! 👏  

I've built a [library](https://github.com/justindujardin/pathy) that subclasses pathlib.Path to work with bucket storage, and it uses smart_open to provide the streamable io interface.

When installing smart_open it pulls in the AWS dependencies even if I'm only using it for GCS. I see that you all have setup the package to allow installing only the dependencies for each service, but it seems incomplete?

https://github.com/RaRe-Technologies/smart_open/blob/b6cf769266b34ad2146e9ee67cc56b331ab8e91b/setup.py#L88-L91

I found this comment about the extra dependencies being temporary, and I wonder if you have a timeline for a release that removes this?

**Comment by piskvorky** [comment]
I don't think there's any timeline, but being more modular in installing extras is something we'd like to do. Are you able to open a PR?

Related to #463.

**Comment by justindujardin** [comment]
Sure, I opened a PR with a first pass: https://github.com/RaRe-Technologies/smart_open/pull/534
