### ISSUE TITLE
ClientError: An error occurred (413) when calling the UploadPart operation: Request Entity Too Large

### ISSUE THREAD

**Issue by luckydonald** [RaRe-Technologies/smart_open#535]
#### Problem description

Be sure your description clearly answers the following questions:

- What are you trying to achieve?
Upload an apparently too large file.

- What is the expected result?
The file is uploaded.

Having `UploadPart`s, I would files are splits into parts anyway, and those chosen too large.
They should be decreased in size after an `Entity Too Large` Error.

- What are you seeing instead?
```py
ClientError: An error occurred (413) when calling the UploadPart operation: Request Entity Too Large
```

#### Steps/code to reproduce the problem

In order for us to be able to solve your problem, we have to be able to reproduce it on our end.
Without reproducing the problem, it is unlikely that we'll be able to help you.

Include full tracebacks, logs and datasets if necessary.
Please keep the examples minimal ([minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)).

Sample file:
```bash
youtube-dl https://redd.it//ijh0he
```

Selfhosted Minimo behind a Nginx proxy

#### Versions

Please provide the output of:

```python
Python 3.7.7 (default, Mar 31 2020, 15:46:29) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, sys, smart_open
>>> print(platform.platform())
Linux-5.3.0-26-generic-x86_64-with-debian-10.3
>>> print("Python", sys.version)
Python 3.7.7 (default, Mar 31 2020, 15:46:29) 
[GCC 8.3.0]
>>> print("smart_open", smart_open.__version__)
smart_open 2.1.1
```

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [ ] Provided a minimal reproducible example, including any required data
- [ ] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Can you please post some source code that reproduces your problem? It's not clear where are you trying to upload to.
