### ISSUE TITLE
2.2.0 minor release introduces breaking changes

### ISSUE THREAD

**Issue by johntmyers** [RaRe-Technologies/smart_open#540]
Hi,

I am generally curious as to why `2.2.0` was released with such a breaking change to installation / usage for a minor version vs a major version? Also the release notes are not accurate as `aws` is not a valid extra for installation.

**Comment by mpenkov** [comment]
Thank you for pointing this out @johntmyers . Sounds like we failed to increment the version number correctly (again, argh).

@piskvorky I think the way forward is:

1. Release 2.2.1 with the old dependency behavior
2. Fix release notes (the extra name is s3, not aws. The README is correct, but release notes are wrong)
2. Release 3.0.0 with the new dependency behavior

WDYT?

**Comment by piskvorky** [comment]
I agree. Such major breaking changes should come in a major release. How much work is reverting for 2.2.1?

Because the other option is to scratch (delete) 2.2.0 and release 3.0.0 outright.

**Comment by mpenkov** [comment]
https://pypi.org/project/smart-open/2.2.1/
