### ISSUE TITLE
Cached reads

### ISSUE THREAD

**Issue by AndreaCrotti** [RaRe-Technologies/smart_open#56]
The fact that smart_open is streaming is great and nice to use.

However sometimes we still need to get the whole file.

Would there be a way to actually cache the file content, to make sure that we don't actually re-read the whole file every time?

S3 files for example in our case never change, passing around the smart_open read object they would be re-read completely every time right?

Something like

```python
smart_open.smart_open('s3://bucket/key', cached=True)
```

for example could be a possible API for this?
Do you think it's feasible/desirable?

**Comment by AndreaCrotti** [comment]
Actually this can be solved quite simply like this
```python

@cachetools.cached(cache={})
def cached_streamer(file_path):
    """Given a path read the whole thing upfront and cache the result
    so that it does not need to be re-read again
    """
    return [line for line in smart_open.smart_open(file_path)]

```

Even if this is really make sense only for quite small files that can be actually loaded in memory, so I think using the smart_open internals something much smarter could be done..

**Comment by val314159** [comment]
if you wanted to go really nuts, you could start adding stuff to make it a
block filesystem, then those could be cached.

**Comment by AndreaCrotti** [comment]
I'll close this I guess not as interesting and can be easily solved on top of smart_open anyway
