### ISSUE TITLE
[S3 open] Is there a way to do range read other than seek?

### ISSUE THREAD

**Issue by rkooo567** [RaRe-Technologies/smart_open#563]
#### Problem description

I am trying to read X-Y bytes using the S3 open method. Based on the document, it seems like I could specify args for `Object.get` using a `object_kwargs` key inside `transport_params`. But when I specified,

```python3
transport_params={"object_kwargs": "Range": "X-Y"}
```

It seems like this value is always overwritten by Range values overwritten by seek. https://github.com/RaRe-Technologies/smart_open/blob/2f1d1e605d8811abe64e35bb98e7c53d62c298b5/smart_open/s3.py#L379

The problem of seek for my case is that seek seems to read bytes from `offset-EOF`. I'd like to read exactly from `offset-Y` range to avoid read amplification.

Is there any way to achieve this? 

#### Steps/code to reproduce the problem

```python3
URL = "s3://path/to/file/key"
offset = 30
obj_size = 50
with. open(URL, "rb", transport_params={"defer_seek": True, "object_kwargs": {"Range": f"{offset}-{offset+object_size}"}}) as f:
  a = f.read(10)  
```

#### Versions

Python 3.7
smartopen 3.0.0

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by ericl** [comment]
@rkooo567 are you sure this is actually the case? Seek seems to work for me here in that it doesn't download all the data:
```
>>> f = smart_open.smart_open("s3://ray-wheels/latest/ray-1.1.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl")
>>> s = time.time(); f.seek(1000000); len(f.read(10)); time.time() - s
1000000
10
0.27358365058898926
>>> s = time.time(); f.seek(0); len(f.read()); time.time() - s
0
25652108
2.845583915710449
```

**Comment by rkooo567** [comment]
Hmm based on code, it definitely reads from seeked position - EOF. https://github.com/RaRe-Technologies/smart_open/blob/2f1d1e605d8811abe64e35bb98e7c53d62c298b5/smart_open/s3.py#L379

Your example doesn't guarantee that it will download only 10 bytes of data right? This will still download the range `1000000 -EOF`

**Comment by ericl** [comment]
It's not physically possible on my network connection to download the entire wheel in 270ms, so it must be reading a smaller range there. I'm guessing it reads up to some buffer size.

**Comment by rkooo567** [comment]
Turns out there was my misunderstanding somewhere. Maybe Object.get API doesn't read the whole bytes right away.
