### ISSUE TITLE
[Feature request] Support for Databricks (Databricks FileSystem)

### ISSUE THREAD

**Issue by Rhuax** [RaRe-Technologies/smart_open#566]
Hi, super awesome library!
I would know if is it planned, in the future, the support for Databricks and the Databricks filesystem.

**Comment by piskvorky** [comment]
Not planned, no. But if someone contributes an implementation, with strong motivation, documentation, testing etc, we'll consider it.

**Comment by Rhuax** [comment]
Ok! I close the issue since my question has received an answer
