### ISSUE TITLE
Seek in write mode [io.UnsupportedOperation: seek]

### ISSUE THREAD

**Issue by nakashkumar** [RaRe-Technologies/smart_open#580]
`with smart_open.open('s3://...', 'wb') as fout:
    fout.seek(0)`

I can seek in read mode but not write. It works with primitive open.
I am getting `io.UnsupportedOperation: seek`

**Comment by mpenkov** [comment]
I'm not sure if it's possible to support this with boto3 (the library we use for connecting to S3) or even S3 in general.

The stream abstraction that smart_open offers is just that: an abstraction. Under the covers, smart_open performs a multi-part file upload. From what I understand, it isn't possible to change arbitrary parts of an existing object on S3: you'd have to overwrite it completely.

Please let me know if I'm wrong (or if you'd like to take this up as a PR).
