### ISSUE TITLE
io.UnsupportedOperation when calling tell()

### ISSUE THREAD

**Issue by quantumfusion** [RaRe-Technologies/smart_open#581]
#### Problem description

Performing a `file_obj.tell()` on a file object returned by `smart_open.open` results in an error in the 4.1.2 release. However, when I switch to the previous 4.1.0 release, this does not occur. A quick search seems to point to #578 which introduces use of `io.TextIOWrapper`. Calling `tell()` is not using the underlying `tell()` from the cloud specific writers. The original codecs implementation inherits functions like `tell()` from the file object that is passed in.

#### Steps/code to reproduce the problem

```python
cloud_location = 's3://examplebucket/foobar'
import smart_open
with smart_open.open(cloud_location, 'w') as f:
    print(f.tell())
```

Above code with a valid `cloud_location` throws the following:
```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
io.UnsupportedOperation: underlying stream is not seekable
```

#### Versions

Linux-5.4.0-1029-aws-x86_64-with-glibc2.29
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
smart_open 4.1.2

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
@markopy Are you able to take a look at this?

**Comment by markopy** [comment]
Strange, from a quick look at `TextIOWrapper` it should be calling the underlaying `tell()`. I will add some additional tests and investigate.

**Comment by markopy** [comment]
The problem was that the writers for cloud storage did not indicate support for `tell()` by implementing `seekable()`. I have created PR #582 as fix.

Note however that per python spec (https://docs.python.org/3/library/io.html#io.TextIOBase.tell) `tell()` returns and opaque number in text mode which is only useful to return to the same position via `seek()`:

> seek(offset, whence=SEEK_SET)
> Change the stream position to the given offset. Behaviour depends on the whence parameter. The default value for whence is SEEK_SET.
> 
> SEEK_SET or 0: seek from the start of the stream (the default); offset must either be a number returned by TextIOBase.tell(), or zero. Any other offset value produces undefined behaviour.
> 
> SEEK_CUR or 1: “seek” to the current position; offset must be zero, which is a no-operation (all other values are unsupported).
> 
> SEEK_END or 2: seek to the end of the stream; offset must be zero (all other values are unsupported).
> 
> Return the new absolute position as an opaque number.
> 

> tell()
> Return the current stream position as an opaque number. The number does not usually represent a number of bytes in the underlying binary storage.
> 

smart_open does not implement `seek()` for any of the cloud writers so whatever you are doing with the `tell()` return value is probably only working by accident @quantumfusion 

Perhaps we should actually not support `tell()` until `seek()` is implemented as well?

**Comment by quantumfusion** [comment]
Ah, thanks for looking into this. We have some code that was using `tell()` as a lazy way of logging that some stuff was actually written and not using it for any `seek()` behavior. Part of the motivation for creating the ticket was noticing the `tell()` implementation in `s3.py`.

**Comment by markopy** [comment]
`tell()` will give you the bytes written if you open the file in binary mode but I don't think that's a guarantee that they are actually on s3 servers yet.

`flush()` would be the appropriate thing to call for that but unfortunately it's a noop in smart_open.

**Comment by quantumfusion** [comment]
I see. Thanks for the clarification. Sounds like we need to go through and clean up our usage of `tell()`. Luckily it seems to only be used for a bunch of logging...
