### ISSUE TITLE
Read from Github API

### ISSUE THREAD

**Issue by ryan-schreiber** [RaRe-Technologies/smart_open#585]
This is a feature request/question.

I was wondering if you guys had any development plans to support reading/calls to the github api? I was able to implement a relatively simple [extension of the http module's open](https://github.com/ryan-schreiber/smart_open/commit/6b0256b185f71f62513cc06ea42b036cab322b22#diff-e868a495dbb739de09c2ca4fddad1868e2aa691ad89682bc7328fdb388b2d031), and it works well for uncompressed files (also I realize that it would be simple enough for a user just to pass the bearer api token as header, read, json.loads, and decode so might or might not necessarily be a valuable code addition for this use case). However, this does not work well for compressed files, and in the user flow users wouldn't be able to leverage the built in decompression.

A use case I could see this being very helpful is an ETL flow of a version controlled compressed csv in a private repo. It would operate something like below (fake file path):

```python
import pandas, os
from smart_open import open

url = "https://api.github.com/repos/<owner>/<repo>/contents/data_file.bz2"
with open(url, transport_params={"git_token" : os.environ.get("TOKEN","")} ) as file_object:
    df = pandas.read_csv(file_object)

# transforms and writes
...

```

Also with github, writing would be a bit of an issue with needing to specify a commit message and generally not wanting to push one file at a time. So I thought it made sense to fall into the http module because it is already read only.

**Comment by mpenkov** [comment]
No, not really. I don't think the benefits justify the cost. For example, the abstraction that smart_open uses is streaming. In this particular case, this abstraction doesn't fit well with github in the write case, as you have correctly pointed out.

For people that need read stuff from github, HTTPS approach you detailed is probably good enough. Would you be interested in adding that to the howtos.md file in a PR?

**Comment by ryan-schreiber** [comment]
Gotcha, yeah that makes sense. Reading in a full response, modifying, and wrapping in a stream isn't exactly the same thing as a proper stream haha. 

Sure, yeah I'll add a section in that file about the http approach above and create a PR.

**Comment by ryan-schreiber** [comment]
I see that it's merged in so going to close the issue.
