### ISSUE TITLE
readlines on files from hdfs using webhdfs hangs

### ISSUE THREAD

**Issue by traboukos** [RaRe-Technologies/smart_open#592]
#### Problem description

readlines on files from hdfs using webhdfs hangs

#### Steps/code to reproduce the problem

```python
with open("webhdfs://namenode/myfile.txt", "r") as f:
    lines = f.readlines()
```

The issue seems to be in the following line 
https://github.com/RaRe-Technologies/smart_open/blob/develop/smart_open/webhdfs.py#L147

Sometimes ```self._response.raw.read(io.DEFAULT_BUFFER_SIZE)``` returns 0 bytes and StopIteration is never thrown resulting in the call hanging for ever. I fixed it locally with the following change which seems to work.

```python
while len(self._buf) < size:
    raw_data = self._response.raw.read(io.DEFAULT_BUFFER_SIZE)
    if len(raw_data) == 0:
        break

    self._buf += raw_data
```

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```
Linux-5.8.0-44-generic-x86_64-with-debian-bullseye-sid
Python 3.7.3 (default, Sep  3 2020, 16:41:28)
[GCC 9.3.0]
smart_open 4.2.0

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
Thank you for reporting this. Are you able to make a PR with a fix?

**Comment by traboukos** [comment]
Yes can do if you are ok with the fix described above.

**Comment by mpenkov** [comment]
I think a simpler way is to change one line:

    while 0 < len(self._buf) < size:

Right?

**Comment by piskvorky** [comment]
```python
self._buf += raw_data
```

This looks like an anti-pattern. I'm not familiar with the rest of the code, but isn't the standard pattern of append-to-list-then-join-at-the-end preferable?

**Comment by mpenkov** [comment]
Not sure what you mean, could you please elaborate?

**Comment by piskvorky** [comment]
Edited my post above.

**Comment by mpenkov** [comment]
Yes, you're right, string concatenation is awful.

The approach you suggest is definitely better. Another common way to to it is to write into an io.BytesIO buffer.

@traboukos Please go ahead with the PR, taking the above into account.

**Comment by traboukos** [comment]
OK @mpenkov @piskvorky makes sense. Will send a pr.
