### ISSUE TITLE
ImportError: cannot import name version

### ISSUE THREAD

**Issue by ghost** [RaRe-Technologies/smart_open#596]
I try to install a module named "seq2seq" which use smart_open but when I try to run it I have this errror message "from smart_open import version
ImportError: cannot import name version"

Could someone help me please ?
Thank you.

**Comment by mpenkov** [comment]
Are you using pip to install packages? What is the output of `pip show smart_open`?

**Comment by AmirUCR** [comment]
I had the same issue, but with node2vec on Python 2.7. Installing an older release of smart_open solved the issue. Looking at seq2seq's repo, it was updated last around March 2017. See here https://pypi.org/project/smart-open/#history - do the following 

`pip uninstall smart_open`
`pip install smart_open==1.4.0`

Run seq2seq again, see what happens.

**Comment by FalconMadhab** [comment]
Yes, degrading the version helped. Thanks @AmirUCR
