### ISSUE TITLE
Writing to S3 with server-side encryption doesn't work anymore

### ISSUE THREAD

**Issue by challisd** [RaRe-Technologies/smart_open#606]
#### Problem description
Earlier versions of smart_open (I've tested v1.11.1 and v3.0.0) allowed writing to S3 with server-side encryption like this:
```python
output_handle = smart_open.open(out_url, "w", transport_params={         'multipart_upload_kwargs': {             'ServerSideEncryption': 'AES256'         }})
```

In the latest versions this doesn't work and I cannot find any documentation or figure out a different way of making it work. The result is I get an error like `ValueError: the bucket 'myBucket' does not exist, or is forbidden for access (ClientError('An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied'))`

#### Steps/code to reproduce the problem

- install the latest version of smart_open
- create an output handle as shown above

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```
Linux-4.4.0-17763-Microsoft-x86_64-with-glibc2.10
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0]
smart_open 5.0.0

#### Checklist

Before you create the issue, please make sure you have:

- [X] Described the problem clearly
- [X] Provided a minimal reproducible example, including any required data
- [X] Provided the version numbers of the relevant software

**Comment by pepastach** [comment]
smart_open version 5.0.0 changes `transport_params`. See https://github.com/RaRe-Technologies/smart_open/blob/v5.0.0/MIGRATING_FROM_OLDER_VERSIONS.rst

**Comment by mpenkov** [comment]
Try this:

```python
client_kwargs = {
  'S3.Client.create_multipart_upload': {
    'ServerSideEncryption': 'AES256',
  }
}
writer = smart_open.open(url, 'w', transport_params={'client_kwargs': client_kwargs})
```

**Comment by challisd** [comment]
It works! Thank you!

**Comment by challisd** [comment]
I should note that it works fine in Python 3.8. The same code does not work in python 3.7 for some reason

**Comment by mpenkov** [comment]
Can ypu please be more specific? What does not work? Is there an exception?

**Comment by challisd** [comment]
Sure, when I run this:
```Python
import smart_open
client_kwargs = {'S3.Client.create_multipart_upload': {'ServerSideEncryption': 'AES256'}}
writer = smart_open.open("s3://bucket-name/path/to/file.txt", 'w', transport_params={'client_kwargs': client_kwargs})
writer.write("nothing to see here\n")
writer.close()
```
I get this error:
```
ValueError: the bucket 'bucket-name' does not exist, or is forbidden for access (ClientError('An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied'))
```
The same exact code writing to the same location works fine in Python 3.8 but gives this error with Python 3.7

**Comment by challisd** [comment]
Sadly no, my old WSL environment got deleted with the last Windows 10 upgrade (thanks Microsoft!)
