### ISSUE TITLE
Assuming role/user doesn't work in smart_open.open

### ISSUE THREAD

**Issue by lesagi** [RaRe-Technologies/smart_open#610]
#### Problem description

I'm using the smart_open.open method to stream items data from S3 to use in my code.

According to the docs, if I want to access the service with different credentials that the system user profile, this is how it's supposed to be done:
```python
session = boto3.Session(
    aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
    aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])

path="mybucket/file.json"
with smart_open.open(f"s3://{path}", mode='r', transport_params={'client': session.client('s3')}) as file:
    for line in file:
        print(json.loads(line))
```

But that just throws the following error:
```
unable to access bucket: 'mybucket' key: 'file.json' version: None error: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

The user that owns these credentials has all the necessary permissions. I know that because when I have tried to set the system profile to that user it worked fine.

Does anyone know how to solve this?
Thanks

#### Steps/code to reproduce the problem

1. Create a user/role in AWS that has full control on S3 (for the sake of reproducing the problem)
2. Verify that the current AWS profile is different from the new role you set (run ```aws sts get-caller-identity```)
3. Try to read the content of a file that is hosted on S3 bucket with smart_open.open (like shown above)

#### Versions

Windows-10-10.0.18362-SP0
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
smart_open 3.0.0

#### Checklist

Before you create the issue, please make sure you have:

- [v] Described the problem clearly
- [v] Provided a minimal reproducible example, including any required data
- [v] Provided the version numbers of the relevant software

**Comment by lesagi** [comment]
So, I have a solution to this issue.
After digging into the library code, the docs are misleading (as far as I can tell).
Instead of passing the actual client, you need to pass the session. The following works:

```python
session = boto3.Session(
    aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'],
    aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])

with smart_open.open(f"s3://{path}", mode='r', transport_params={'session': session}) as file:
    for line in file:
        print(json.loads(line))
```

**Comment by mpenkov** [comment]
The current version of smart_open is 5.0. You're using 3.0.

**Comment by lesagi** [comment]
I see, thanks!
