### ISSUE TITLE
Travis tests sometimes hang

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/smart_open#62]
The Travis CI tests sometimes hang, and this may be indicative of a bug in `s3_iter_bucket` routine, which uses multiprocessing.

The failing tests mess up unrelated PRs (need manual test restarts, like in #61), so we want this fixed ASAP.

**Comment by menshikh-iv** [comment]
@piskvorky I have not seen hangs lately, it's still relevant?

**Comment by menshikh-iv** [comment]
Yes, relevant, reproduced with Travis, problem in `test_s3_iter_bucket_moto (smart_open.tests.test_smart_open.S3IterBucketTest)`

**Comment by mpenkov** [comment]
We don't use Travis anymore.
