### ISSUE TITLE
Is there a smart_delete?

### ISSUE THREAD

**Issue by YutingZhang** [RaRe-Technologies/smart_open#629]
This is just a question. Is there a `smart_delete` function that can remove a file both locally and remotely? That is to say a generalization of `os.remove` as `smart_open` does for `open`. Thanks

**Comment by mpenkov** [comment]
No, not in this library.

**Comment by dvmorris** [comment]
Is there another library you would suggest that would have the equivalent functionality to smart_open, but would delete the objects?

**Comment by mpenkov** [comment]
I can't think of a single library.

- For local files, rm -rf obviously works
- For S3, I use "aws s3 rm --recursive"
- For other platforms, I don't really care, because I don't use them ;)

**Comment by dvmorris** [comment]
I found one through the ray-project: https://arrow.apache.org/docs/python/filesystems.html
