### ISSUE TITLE
PEP 440 Complains when using Poetry tooling

### ISSUE THREAD

**Issue by lucasvieirasilva** [RaRe-Technologies/smart_open#638]
#### Problem description

The newer version of [poetry](https://pypi.org/project/poetry/1.2.0a2/) uses the PEP 440 to validate the versions in the package, and when I tried to install the `smart_open==5.1.0` the latest version, I'm getting this error:

```text
  ValueError

  Could not parse version constraint: >=3.6.*
```

#### Steps/code to reproduce the problem

1. Using the poetry version `1.2.0a2`
2. Run command `poetry install smart-open==5.1.0 --extras "s3"`

#### Versions

- **Poetry**: `1.2.0a2`
- **Python**: `3.8.11`
- **Smart-open**: `5.1.0`

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by piskvorky** [comment]
Thanks for the clear description! This issue should be fixed by #631 (plus a new release).
