### ISSUE TITLE
How to disable multipart_upload S3 writer?

### ISSUE THREAD

**Issue by danielloader** [RaRe-Technologies/smart_open#641]
I've had a dig through the docs and source code but I can't see an easy way to force the use of a put object call instead of multipart upload - I'm trying to write to a bucket where I don't have multipart permissions so if I could enforce single puts that would be great.

Thanks

**Comment by piskvorky** [comment]
>  I'm trying to write to a bucket where I don't have multipart permissions so if I could enforce single puts 

That's an interesting use-case. But a single PUT kinda goes against the reason for `smart_open`'s existence (data streaming). So I'm not sure it's a good fit – @mpenkov WDYT?

**Comment by danielloader** [comment]
Yeah I agree it's a weird use case, I guess I can call the s3.open method directly with the multipart_upload=False argument if need be. Since the files being uploaded are sub 5MB profiling the AWS lambda function a single PUT seems more efficient but if that's not the ethos of the library I'll just defer back to boto3 directly.

Thanks

**Comment by mpenkov** [comment]
Why is setting multipart_upload not an acceptable solution?

**Comment by danielloader** [comment]
Can you do that from the main entrypoint, `from smart_open import open`? or do you have to import the s3 open directly and go from there?

**Comment by mpenkov** [comment]
> Can you do that from the main entrypoint, from smart_open import open? 

Yes.

```python
from smart_open import open
with open("s3://bucket/key", "wb", transport_params={"multipart_upload": False}) as fout:
    ...
```

**Comment by danielloader** [comment]
Perfect, that's exactly what I needed!, thank you.

**Comment by piskvorky** [comment]
Thanks @mpenkov as always! Closing here – @danielloader let us know if you hit any issues.
