### ISSUE TITLE
Request Support for `viewfs://`

### ISSUE THREAD

**Issue by zhezh** [RaRe-Technologies/smart_open#645]
#### Problem description

Hi, smart_open currently supports `hdfs://`, `viewfs://` is also a hadoop file system which is similar to `hdfs://`.

I find that `tf.io.gfile.GFile` of tensorflow can support both `hdfs://` and `viewfs://`, is it possible that smart_open add support for `viewfs://`?

Thanks~

**Comment by mpenkov** [comment]
It's possible, but only if someone steps up and implements it in a PR.
