### ISSUE TITLE
Feature request: extracting tar archives to S3

### ISSUE THREAD

**Issue by xegulon** [RaRe-Technologies/smart_open#653]
#### Problem description

I'd like to be able to open and extract tarfiles directly from/to AWS S3. A syntax of this kind would be convenient:

```python
from smart_open import tarfile
with tarfile.open('s3://my-bucket/some-targz-archive.tar.gz', 'rb', 
                  transport_params={'client': session.client('s3')}) as tar:
       tar.extractall('s3://some-bucket/some-folder/')
```

For now, how should I manage that?

**Comment by mpenkov** [comment]
Something like:

```python
with smart_open.open('s3://bucket/file.tar.gz', 'rb', compression='ignore') as fin:
   with tarfile.open(fileobj=fin) as tar:
       for member in tar.getmembers():
         with smart_open.open(f's3://bucket/destination/{member.name}') as fout:
             ... # read from member, write to fout
```

Note that this will still buffer parts of the tar file locally to your machine, so it won't be really "directly from/to AWS S3", but it's as close as you're going to get.

**Comment by xegulon** [comment]
Thanks, what about having an abstraction for that in the lib?

**Comment by mpenkov** [comment]
I think that's out of scope for smart_open, especially given that it already works (or should work, anyway) as demonstrated in the untested pseudo-code above.

**Comment by xegulon** [comment]
I see. Anyway, it would be great to have a tool that enables us to do basic python operations on files and directories indistinctly of the filesystem's type: local or remote. I am thinking of functions like `os.listdir, os.exists, os.isdir, tarfile.open, tar.extractall`, etc.

One would have a base filesystem class, defaulting to the local filesystem, with subclasses corresponding to different kinds of storages (S3, GCS, Azure) and initialized using credential keys. That layer of abstraction is relevant for some of my use cases. `smart_open` manages the `open` API, it would be great to extend the idea to other APIs.

I'm not 100% sure it would be the best way of implementing that though. Thanks again!

**Comment by adgilbert** [comment]
For anyone stumbling on this, the correct syntax is now: 
```python
with smart_open.open('s3://bucket/file.tar.gz', 'rb', compression='disable') as fin:
    ...
```
