### ISSUE TITLE
Stop smart_open.open() from uploading file to s3 if file is already opened

### ISSUE THREAD

**Issue by loganbonsignore** [RaRe-Technologies/smart_open#666]
I am opening an S3 file with:

```python
fh = smart_open.open(filename, mode, transport_params=dict(client=init_s3_client()))
```

Then later writing to the file before closing it and kicking off the file upload:
```python
fh.write(b"this is data")
fh.close()
```

When the writing is complete and smart_open is ready to upload the file to s3, is there a way to cancel the file upload if it's contents are empty? Perhaps if the file is 0 bytes in size? Thank you.

**Comment by mpenkov** [comment]
Why did you close this?

**Comment by loganbonsignore** [comment]
I found a way around it in the project i am working on. The solution is unrelated to smart_open. Figured I would close. I am happy to keep open if you are interested in working on it.

**Comment by mpenkov** [comment]
OK, glad you found a workaround. Let's keep the issue closed for now.
