### ISSUE TITLE
Can we set TransferConfig options for bandwidth control on a download?

### ISSUE THREAD

**Issue by flaker** [RaRe-Technologies/smart_open#674]
#### Problem description

Be sure your description clearly answers the following questions:

- I'd like to set `max_bandwidth` in the TransferConfig option but I fail to see where that could be done. Reading ` s3.py` I see how to send extra config options to the client but no how/where to set TransferConfig.

Is it possible at all?

#### Versions

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ]
smart_open 5.2.1

```

**Comment by mpenkov** [comment]
smart_open does not use s3.tranfer, so max_bandwidth isn't an option that we could support.

This is the API we use:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#client

If you can find bandwidth-related options there, let us know.

**Comment by flaker** [comment]
It seems that the max_bandwidth option can only be used with `TransferConfig` and that can only be provided to:
 - `download_file`
 - `download_fileobj`
 - `upload_file`
 - `upload_fileobj`
 - `copy`

if I am not mistaken, smart_open uses `get_object` correct? so there is no way to set the transfer options in `TransferConfig`.

**Comment by mpenkov** [comment]
Yes.

**Comment by flaker** [comment]
closing since it seems to the current implementation is not really using the required config.
