### ISSUE TITLE
smart_open.http missing "requests" requirement

### ISSUE THREAD

**Issue by jcdoig** [RaRe-Technologies/smart_open#677]
#### Problem description

A missing dependency error showed up indicating that I should install smart_open[http]

The error is generated when the "Requests" package is missing. see lines 15-18 in http.py

```
try:
    import requests
except ImportError:
    MISSING_DEPS = True
```

The error does not communicate the real issue. Also, I could not find any clear indication that "Requests" was a dependency in the package documentation.

Be sure your description clearly answers the following questions:

- What are you trying to achieve?

I was trying the run_corpora_and_vector_spaces tutorial

- What is the expected result?

No exceptions

- What are you seeing instead?

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/lv/p23djszn11d5fyr3s059xdp80000gn/T/ipykernel_28770/740319349.py in <module>
----> 1 for vector in corpus_memory_friendly:  # load one vector into memory at a time
      2     print(vector)

/var/folders/lv/p23djszn11d5fyr3s059xdp80000gn/T/ipykernel_28770/2068793025.py in __iter__(self)
      4 class MyCorpus:
      5     def __iter__(self):
----> 6         for line in open('https://radimrehurek.com/mycorpus.txt'):
      7             # assume there's one document per line, tokens separated by whitespace
      8             yield dictionary.doc2bow(line.lower().split())

~/.pyenv/versions/3.10.0/envs/Gensim-Tutorial/lib/python3.10/site-packages/smart_open/smart_open_lib.py in open(uri, mode, buffering, encoding, errors, newline, closefd, opener, ignore_ext, compression, transport_params)
    233         raise NotImplementedError(ve.args[0])
    234 
--> 235     binary = _open_binary_stream(uri, binary_mode, transport_params)
    236     decompressed = so_compression.compression_wrapper(binary, binary_mode, compression)
    237 

~/.pyenv/versions/3.10.0/envs/Gensim-Tutorial/lib/python3.10/site-packages/smart_open/smart_open_lib.py in _open_binary_stream(uri, mode, transport_params)
    395 
    396     scheme = _sniff_scheme(uri)
--> 397     submodule = transport.get_transport(scheme)
    398     fobj = submodule.open_uri(uri, mode, transport_params)
    399     if not hasattr(fobj, 'name'):

~/.pyenv/versions/3.10.0/envs/Gensim-Tutorial/lib/python3.10/site-packages/smart_open/transport.py in get_transport(scheme)
     88     )
     89     if scheme in _ERRORS:
---> 90         raise ImportError(_MISSING_DEPS_ERROR % dict(module=_ERRORS[scheme]))
     91     if scheme in _REGISTRY:
     92         return _REGISTRY[scheme]

ImportError: You are trying to use the http functionality of smart_open
but you do not have the correct http dependencies installed. Try:

    pip install smart_open[http]
```

#### Steps/code to reproduce the problem

In order for us to be able to solve your problem, we have to be able to reproduce it on our end.
Without reproducing the problem, it is unlikely that we'll be able to help you.

Include full tracebacks, logs and datasets if necessary.
Please keep the examples minimal ([minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)).

Clean Pyenv Virtualenv with pip install gensim, trying the following tutorial
https://radimrehurek.com/gensim/auto_examples/core/run_corpora_and_vector_spaces.html

#### Versions

Please provide the output of:

```python
import platform, sys, smart_open
print(platform.platform())
print("Python", sys.version)
print("smart_open", smart_open.__version__)
```

macOS-12.1-arm64-arm-64bit
Python 3.10.0 (default, Dec 17 2021, 20:03:12) [Clang 13.0.0 (clang-1300.0.29.30)]
smart_open 5.2.1

#### Checklist

Before you create the issue, please make sure you have:

- [x] Described the problem clearly
- [x] Provided a minimal reproducible example, including any required data
- [x] Provided the version numbers of the relevant software

**Comment by mpenkov** [comment]
https://github.com/RaRe-Technologies/smart_open#installation

If you want to use HTTP, install smart_open via:

    pip install smart_open[http]

The requests library is an optional extra that gets used for HTTP (and some other things).

**Comment by jcdoig** [comment]
I think the error message is confusing (and in that sense, unhelpful) because it tells the user that smart_open[http] is missing even when it is properly installed.

In my case smart_open[http] was already present in my virtual environment. When I tried to install it I received the following message.

```
Requirement already satisfied: requests in /Users/jcdoig/.pyenv/versions/3.10.0/envs/Gensim-Tutorial/lib/python3.10/site-packages (from smart_open[http]) (2.26.0)
```

The problem is that the way the code is written makes Requests (**_effectively_**) a dependency, even if you want it to be optional. Let me elaborate.

in transport.py, line 100, the code attempts to register the module.
```
register_transport('smart_open.http')
```

if "Requests" is missing, the http module registration will always fail. It fails because line 15 in http.py reports MISSING_DEPS = True.
```
try:
    import requests
except ImportError:
    MISSING_DEPS = True
```

Thus the missing dependency is not **smart_open[http]** but **requests**

I understand that Request is only used for extra functionalities, but effectively, the code does not run if it is not installed.

This might, or might not, be the cause for #560 

Thanks for all your work on this project!

**Comment by mpenkov** [comment]
> I think the error message is confusing (and in that sense, unhelpful) because it tells the user that smart_open[http] is missing even when it is properly installed.

I don't think what you're saying is possible.  If smart_open[http] (read: requests) is installed, then that message will appear.
Please show me the output of these commands to make sure we're on the same page:

```
pip freeze
python -c 'from smart_open import open;print(open("http://example.com").readline())'
```

> if "Requests" is missing, the http module registration will always fail. It fails because line 15 in http.py reports MISSING_DEPS = True.

That's a non-fatal failure. smart_open still works without the http module, so it's not a dependency.

Have a look at this:

```bash
(test) misha@cabron:/tmp$ pip freeze  # confirm clean environment
(test) misha@cabron:/tmp$ pip install smart_open  # install minimum smart_open
Collecting smart_open
  Using cached smart_open-5.2.1-py3-none-any.whl (58 kB)
Installing collected packages: smart-open
Successfully installed smart-open-5.2.1
(test) misha@cabron:/tmp$ python -c 'import smart_open'
(test) misha@cabron:/tmp$ python -c 'from smart_open import open;print(open("http://example.com").readline())'  # try opening HTTP URL, fails as expected
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/misha/envs/test/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 235, in open
    binary = _open_binary_stream(uri, binary_mode, transport_params)
  File "/home/misha/envs/test/lib/python3.9/site-packages/smart_open/smart_open_lib.py", line 397, in _open_binary_stream
    submodule = transport.get_transport(scheme)
  File "/home/misha/envs/test/lib/python3.9/site-packages/smart_open/transport.py", line 90, in get_transport
    raise ImportError(_MISSING_DEPS_ERROR % dict(module=_ERRORS[scheme]))
ImportError: You are trying to use the http functionality of smart_open
but you do not have the correct http dependencies installed. Try:

    pip install smart_open[http]


(test) misha@cabron:/tmp$ pip install smart_open[http]  # do what the error message says
Requirement already satisfied: smart_open[http] in /home/misha/envs/test/lib/python3.9/site-packages (5.2.1)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.9 idna-3.3 requests-2.26.0 urllib3-1.26.7
(test) misha@cabron:/tmp$ pip freeze
certifi==2021.10.8
charset-normalizer==2.0.9
idna==3.3
requests==2.26.0
smart-open==5.2.1
urllib3==1.26.7
(test) misha@cabron:/tmp$ python -c 'from smart_open import open;print(open("http://example.com").readline())'  # success, hooray!
<!doctype html>
```

> Thus the missing dependency is not smart_open[http] but requests

First, smart_open[http] is not a package, so it cannot be present or missing. It's some pip magic that says "install smart_open, and then install the set of extra packages it calls "http". In this case, that set of packages consists of just requests (but it could, in theory, contain more).  So in this particular case smart_open[http] and requests are synonymous.

In theory, if you were somehow allergic to "smart_open[http]", you could simply do "pip install requests" and it would achieve absolutely the same thing.

> This might, or might not, be the cause for #560

I don't think they are related. It's our CI being weird.

> Thanks for all your work on this project!

You're welcome ;)

**Comment by jcdoig** [comment]
I see, yes I followed the steps you indicated on a new virtual environment and got the same results as you. I don't know why the first time it did not install requests (I must have done something wrong...) I ended up installing requests manually on that other environment earlier today.

Thanks and sorry for taking your time.
