### ISSUE TITLE
[feature request] platform-independent iterdir()

### ISSUE THREAD

**Issue by Dutcho** [RaRe-Technologies/smart_open#680]
#### Problem description

`smart_open`makes `open()`work across storage providers _if_ the user knows the location/path/url/uri of the file to open. Great!

However, to **find** the file still requires knowledge of different storage providers' (equivalent of) `iterdir()` logic. It would be great if `s3.iter_bucket()` (for S3 only) would be generalised into an `iterdir()` that works for each platform supported by `smart_open`.

Then users could use `smart_open` to locate files on a platform **and** open those found files.

#### Alternative approaches

_Partial_ solutions exist on [PyPI](https://pypi.org/):
- [urlpathlib](https://pypi.org/project/urlpathlib/) supports HTTP[S] and local, but **not** cloud or Hadoop, and the project seems stale
- [pathy](https://pypi.org/project/pathy/) supports AWS, Google, and local, but **not** Azure, Hadoop, or web
- [cloudpathlib](https://pypi.org/project/cloudpathlib/) supports AWS, Azure, Google, but **not** Hadoop, web, or local
- [iotoolz](https://pypi.org/project/iotoolz/) support AWS and local, but **not** Azure, Google, Hadoop, or web

So an _integrated_ solution doesn't exist (or I couldn't locate it). Of course, such a future integrated solution could perhaps build on the above partial solutions.

**Comment by mpenkov** [comment]
It's out of scope for smart_open. Have a look at https://github.com/mpenkov/koshka, though, it's somewhat related.

**Comment by Dutcho** [comment]
Thanks for kosha, didn’t know that one.
But it seems s3 + web only, and works to expand
