### ISSUE TITLE
allow passing buffer_size as a transport parameter to the http module

### ISSUE THREAD

**Issue by mullenkamp** [RaRe-Technologies/smart_open#700]
Hello,

I was just looking through your http open module and I noticed that it is not possible to pass a user-defined buffer_size to the open/BufferedInputBase/SeekableBufferedInputBase. It's hard coded to the DEFAULT_BUFFER_SIZE. 
Is there a particular reason why this is not an option to pass as a transport parameter?
A higher buffer_size should make less calls to the requests get response, right?
Thanks!

**Comment by mpenkov** [comment]
I think the reason is probably because nobody has requested this before. Are you interested in making a PR?

**Comment by mullenkamp** [comment]
Sure, I'm happy to make a PR. The modifications don't seem very complicated.

**Comment by mullenkamp** [comment]
I FINALLY made a PR for this simple edit...
#730
