### ISSUE TITLE
When in Zshell - no matches found: smart_open[s3] (pip 22.1.2)

### ISSUE THREAD

**Issue by omersi** [RaRe-Technologies/smart_open#707]
#### Problem description

Pip doesn't find the limited installation for `s3` on ZSH. 

#### Steps/code to reproduce the problem

run 

```bash
$ pip install smart_open[s3]                          
zsh: no matches found: smart_open[s3]
```
in zsh.

It works fine in bash.

**Comment by mpenkov** [comment]
I don't think this problem is with smart_open. It's more likely to be an issue with zsh or something else.

**Comment by markgis** [comment]
ZSH doesn't like special characters so you have to quote it;

`pip install 'smart_open[s3]'`
