### ISSUE TITLE
GCP retry mechanism

### ISSUE THREAD

**Issue by cometta** [RaRe-Technologies/smart_open#710]
i'm using version 6. May i know any example on how to enable retry on flaky internet connection when reading stream from GCP bucket  ?

**Comment by mpenkov** [comment]
There is no existing example code I'm aware of that would help in your case.

@petedannemann may be able to help here.

**Comment by petedannemann** [comment]
smart-open's GCS reader uses google.cloud.storage.Blob under the hood. The network call when reading is done by the Blob's [download_as_bytes](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_download_as_bytes) method in smart open's code [here](https://github.com/RaRe-Technologies/smart_open/blob/60050eb1e27ebf57485556f4480d140b0329b8ea/smart_open/gcs.py#L198). We do not specify a retry in smart-open so we use the default one provided by `download_as_bytes` which you can read more about in the first link provided. If that is not sufficient for your use case, please submit a PR allow the user to provide a retry to the `download_as_bytes` calls used in smart-open.
