### ISSUE TITLE
Streaming file with sftp from any remote site

### ISSUE THREAD

**Issue by dineshbvadhia** [RaRe-Technologies/smart_open#717]
I want to:
a. Stream a file using sftp from a remote site 
b. The remote site (customer) provides sftp credentials only ie. the customer is not asked to provide their cloud or other remote storage details
c. Read the remote file line-by-line
d. File may or may not be stored locally
e. Above is repeated for different customers

Is this possible? Thanks

**Comment by mpenkov** [comment]
Yes.
