### ISSUE TITLE
S3OpenRead ignores the mode of `'r'` opens always in `'rb'`

### ISSUE THREAD

**Issue by vinayan3** [RaRe-Technologies/smart_open#74]
The `S3OpenRead` always returns data as `bytes` in Python 3 which breaks things expecting `str`. The `S3OpenRead` needs to respect `'r'` instead of returning everything as `bytes`.

**Comment by appierys** [comment]
It appears that now `smart_open` supports `'r'` mode in 1.5.4?
However, I found that the speed of reading files drops significantly after smart_open 1.5.4.

For smart_open 1.5.3, the speed is:
`2868923it [01:05, 43987.90it/s]`

while smart_open 1.5.4 is:
`41588it [01:35, 434.05it/s]`
for the same S3 file.

**Comment by menshikh-iv** [comment]
Already fixed (doesn't reproduce with current master fbc82cc04bf92e8c588c49c43ff5aff8234ea87d
