### ISSUE TITLE
S3Path or PureS3Path returns NoSuchKeyExists on open('rb') handle intermittently

### ISSUE THREAD

**Issue by atomey** [RaRe-Technologies/smart_open#762]
Trying to open a file in binary/read write. The file handle then gets redirected to a Flask app send_file, to load the S3 file in a webapp.

I am using this routine successfully in 2 spots but for some reason, one particular report (PDF) that generates on S3 and then displays in the app will always get the NoSuchKeyExists. It happens to be the smallest or quickest report that generates. However I have tried adding sleep or pauses in case this was the problem, but it is intermittent. Sometimes it works, sometimes it doesn't.

#### Steps/code to reproduce the problem
Flow essentially looks like this: 

```
pdf_s3file = db.s3_get_path_obj(practice_id,f_name)
    
    if pdf_s3file.exists():
        db.s3_delete_practice_obj(pdf_s3file)

datasheet = DataSheet(practice, pdf_s3file.open('wb'))

#Do a bunch of stuff here to create PDF data#
return pdf_s3file

pdf_s3file.open('rb')

````
s3_get_path_obj is just using PurePath or S3Path but formatting the inputs for me, and returning the object. Delete parses object and deletes with S3 boto3. 
Datasheet is the custom class which creates the PDF using a library.

Once I hit the last call, ('rb'), it will hit the NoSuchKeyExists about 80% of the time for this report. Other 2 reports, which use exact same logic work basically 90% of the time. 

#### Versions
Windows-10-10.0.19045-SP0
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
smart_open 5.2.1

**Comment by mpenkov** [comment]
I don't see smart_open anywhere in the code sample that you've provided. Where does smart_open come into this?

Please provide a **reproducible** code sample and stack traces, i fyou can.

**Comment by atomey** [comment]
My mistake, I checked and just realized I mistakenly posted this under smart-open but it's actually a dependency of the s3path library. I can move the request over there instead if needed. It looks like smart-open is the culprit however. I put the relevant import for s3path at the top.

```

from s3path import S3Path, PureS3Path, register_configuration_parameter

register_configuration_parameter(
    S3Path(f"/{bucket_name }"),
    parameters={
        'ServerSideEncryption': 'AES256'
    })

def s3_get_path_obj(did, filename='', pure=False):
    bname = f"/{bucket_name}" 
    """Returns either PureS3Path or S3Path object.
    
    Parameters:
            did: Integer of NPI for practice
            optional:
            filename: String of filename if not directory.
            pure: Boolean - Whether to use S3PurePath or S3Path"""
    if pure:
        s3obj = PureS3Path(bname,'practice',did,filename)
    else:
        s3obj = S3Path(bname,'practice',did,filename)
    return s3obj
```

Stack trace:

```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 330, in _get
    return client.get_object(Bucket=bucket, Key=key, Range=range_string)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\botocore\client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\werkzeug\wsgi.py", line 538, in __next__
    data = self.file.read(self.buffer_size)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 610, in read
    self._fill_buffer(size)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 713, in _fill_buffer
    bytes_read = self._buffer.fill(self._raw_reader)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\bytebuffer.py", line 152, in fill
    new_bytes = source.read(size)
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 473, in read
    self._open_body()
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 438, in _open_body
    response = _get(
  File "C:\Users\adame\.virtualenvs\SET-7TiNCuEs\Lib\site-packages\smart_open\s3.py", line 338, in _get
    raise wrapped_error from error
OSError: unable to access bucket: 'smd-set-repo' key: 'practice/1619049558/1619049558.pdf' version: None error: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

**Comment by mpenkov** [comment]
I don't think there's anything smart_open could be doing differently here. boto3 is telling us the object at the specified key does not exist.

If you're seeing different behavior based on timing, then it's possible you're dealing with a race condition, but it's up to you to deal with that (out of scope for smart_open).

**Comment by piskvorky** [comment]
I agree, the race condition is out of our hands, sorry.

I'd also recommend opening the object with a context manager:

```python
with pdf_s3file.open('wb') as fout:
    …
```


The way you do it now, `DataSheet(practice, pdf_s3file.open('wb'))` relies on garbage collector to correctly terminate and clean up the object, which is risky. Especially with cloud storages / external APIs.

**Comment by atomey** [comment]
That was it! I just refactored my code to put in the context safety convention. Not sure why I wasn't using it, I've seen it used many times before but probably rushed this. 

I managed to generate about 15 different reports with the context manager without any exceptions.

Thank you!
