### ISSUE TITLE
Webhdfs uri query is discarded

### ISSUE THREAD

**Issue by ellimilial** [RaRe-Technologies/smart_open#77]
Webhdfs allows passing additional parameters such as user.name through query part of the uri, like so:

> http://HOST:PORT/webhdfs/v1/PATH?[user.name=USER]

At the moment the library simply never uses the query part, making it impossible to use those options when accessing files.

**Comment by piskvorky** [comment]
@ziky90 how did that work?

**Comment by ziky90** [comment]
I am sure that it worked without `user.name` in the uri.
Unfortunately I don't have any webhdfs cluster available right now so validation would take a while for me right now.

**Comment by ellimilial** [comment]
For what it's worth - it's not only about user.name. There are other options that user might want to pass - like custom replication factor, permissions etc.

**Comment by ziky90** [comment]
I agree I might not support all the options, I guess that you can feel free to add all the options you need.
