### ISSUE TITLE
Writing a non-trivial size less than one chunk fails

### ISSUE THREAD

**Issue by thejuan** [RaRe-Technologies/smart_open#87]
Trying to write a non-trivial amount but less than the chunk size (say 500kb) fails with 

> Connection reset by peer
> DEBUG:boto:establishing HTTPS connection: host=test-analytics.s3.amazonaws.com, kwargs={'port': 443, 'timeout': 70}
> DEBUG:boto:Token: None
> DEBUG:boto:StringToSign:
> PUT
> ---
> 
> application/octet-stream
> Thu, 11 Aug 2016 03:35:38 GMT
> /test-analytics/mykey.txt?partNumber=1&uploadId=h_wZktx5teVtch7Ss69B0gaMDKYyHuzJ92CBGLDmNrav_AZ4uFKlJXZwI8Bpmg8t8_zLS70bJNuQGBtJj880XbbPF19od0WMuM8OBGVlrlhO9mhuYF9cmAM2253Vl9LZ
> DEBUG:boto:Signature:
> AWS **************************************
> DEBUG:boto:Final headers: {'Content-Length': '3400000', 'Content-MD5': 'GvkoeM9sWF4kgm51pkdlQw==', 'Expect': '100-Continue', 'Date': 'Thu, 11 Aug 2016 03:35:38 GMT', 'User-Agent': 'Boto/2.42.0 Python/2.7.11+ Linux/4.4.0-31-generic', 'Content-Type': 'application/octet-stream', 'Authorization': u'************************'}
> DEBUG:boto:encountered error exception, reconnecting

```
import logging
logging.basicConfig(level=logging.DEBUG)
import smart_open

with smart_open.smart_open('s3://my-bucket/mykey.txt', 'wb') as fout:
    for n in range(0,100000):
        for line in ['first line', 'second line', 'third line']:
            fout.write(line + '\n')
```

Whilst the example code works fine

```
import logging
logging.basicConfig(level=logging.DEBUG)
import smart_open

with smart_open.smart_open('s3://my-bucket/mykey.txt', 'wb') as fout:
    for line in ['first line', 'second line', 'third line']:
        fout.write(line + '\n')
```

`

**Comment by thejuan** [comment]
boto==2.42.0
bz2file==0.98
click==6.6
pkg-resources==0.0.0
pur==3.0.5
requests==2.11.0
smart-open==1.3.3

**Comment by menshikh-iv** [comment]
Works fine with latest master fbc82cc04bf92e8c588c49c43ff5aff8234ea87d, (need to `encode` str to bytes before writing, because mode is `wb`, or change mode to `w`)
