### ISSUE TITLE
offer 'parents' option: make containing directories if necessary/possible

### ISSUE THREAD

**Issue by gojomo** [RaRe-Technologies/smart_open#88]
It's be nice if there were a `smart_open(..., parents=True)` parameter, which (for local files) would create parent directories, if necessary – much like `mkdir --parents`.

**Comment by tmylk** [comment]
Should it be like [this](http://stackoverflow.com/questions/600268/mkdir-p-functionality-in-python/600612#600612)?

**Comment by gojomo** [comment]
Yes, that seems the right approach to handling the dir-making – of course it'd need to be provided the base-directory for the target file path.

**Comment by menshikh-iv** [comment]
I close this PR, reason: https://github.com/RaRe-Technologies/smart_open/pull/169#issuecomment-359294218.
