### ISSUE TITLE
For s3 file, readline doesn't work after seek(0)

### ISSUE THREAD

**Issue by tejinderss** [RaRe-Technologies/smart_open#95]
If we do .seek(0) on an open s3 file instance and calls the readline on it after, it just keeps on giving the empty string '' back and also the iterator is consumed at that point of time. Please find the code snipped link below:
https://dpaste.de/VXTi

EDIT: Updated with code snippet link to dpaste

**Comment by tmylk** [comment]
hmm. could you add a small code snippet to reproduce?

**Comment by tejinderss** [comment]
Added

**Comment by agent-jay** [comment]
@tejinderss The link is dead. Could you please re-share or embed here?

**Comment by agent-jay** [comment]
I've managed to reproduce the error. Code embedded

```
with smart_open.smart_open('s3://key_id:key_secret@smartopentest/valid_text.txt') as fin :
    fin.read() 
    fin.seek(0)
    fin.readline()
```

The readline() outputs a ' ' instead of the first line

**Comment by agent-jay** [comment]
@tmylk I've tested out the following bit of code, is it a valid solution? I'm not sure why the read_key.close() was there to begin with, and how seek has managed to pass the unit tests all this time
    
def seek(self, offset, whence=0):
        """
        Seek to the specified position.

        Only seeking to the beginning (offset=0) supported for now.

        """
        if whence != 0 or offset != 0:
            raise NotImplementedError("seek other than offset=0 not implemented yet")
        
        # self.read_key.close(fast=True) 

        self._open_reader()
```

**Comment by menshikh-iv** [comment]
Works correctly with current master fbc82cc04bf92e8c588c49c43ff5aff8234ea87d
