### ISSUE TITLE
cant use s3 bucket names with dots

### ISSUE THREAD

**Issue by balihoo-gens** [RaRe-Technologies/smart_open#98]
```
 with smart_open.smart_open('s3://balihoo.fulfillment.dev/retain_7_0/test.txt', 'wb') as f:
    f.write('test')
```
results in:
`ssl.CertificateError: hostname 'balihoo.fulfillment.dev.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'`

I tried to fix this with the 'host' parameter, but I can't get it to write the file.

**Comment by tmylk** [comment]
Hi @balihoo-gens, Does adding `calling_format` fix it as in your previous PR https://github.com/RaRe-Technologies/smart_open/pull/83 ?

**Comment by balihoo-gens** [comment]
ha, will try. That PR is not mine, but by one of my coworkers, @balihoo-dengstrom
I actually ended up using s3fs: https://github.com/dask/s3fs

**Comment by tmylk** [comment]
Thanks for the link. You are not using a proxy, right? Or did s3fs get around https://github.com/boto/boto3/issues/338 ? That is the issue that is blocking us from moving to boto3.

**Comment by balihoo-gens** [comment]
I am using this from an AWS Lambda function

**Comment by mpenkov** [comment]
This looks like a duplicate of Issue #26 @menshikh-iv

**Comment by menshikh-iv** [comment]
@mpenkov yep
@balihoo-gens already fixed in current master
